### ISSUE TITLE
Improve voice definitions and documentation

### ISSUE THREAD

**Issue by Dvogonen** [opentx/opentx#1084]
The definition of which voice files that are used by each language is today only described in the code that automatically generates voice files and in the code that interprets the files. There is no "master list" that describes which file names that must be used for the system strings for each language and neither is there information available about which user definable file names that are preferred.

Neither is there any descriptive information available for the purpose of each voice files. Some are very obvious and need no description. Others are not obvious at all.

All this information ought to be defined in a common place and used by both the code and published on the web.

Suggestion Outline:
Break out the definition of voice files from the current python scripts (not even available for all languages).
Place the definitions in comma separated files. One line per voice file.
Add usage information for some of the voice files.
Add code scripts in python that uses the definitions.
Add a php frontend that publishes the information on a web page on the OpenTX home page.
Add some information on the web page about sound format and naming conventions, so that we have a good place to direct all the voice related questions to.

**Comment by powercycle** [comment]
Wanted to update this, isn't there a CSV file that gets created?  
Locally, I've created scripts that read that generated file and then produce the proper sounds.
That way I can make new ones and if there are changes in the CSV, I just modify my local version to include those.
I'm not clear why the CSV file gets generated, instead of just starting with it from the beginning.
I'll add information regarding sound files and format to the current documentation.
