### ISSUE TITLE
Windows firmware build instructions no longer work

### ISSUE THREAD

**Issue by Dvogonen** [opentx/opentx#1378]
The build instructions for setting up a working OpenTX firmware toolchain on Windows no longer works. They were checked and worked a month or so ago. There are now several different issues. Some might be local to my machine, but not all.

Compiling firmware for 9x works.

Compiling the simulator breaks with the following error message:
c:\src\github\opentx\radio\src>make simu
dd if=/dev/zero of=eeprom.bin bs=1 count=2048
dd: /dev/zero: No such file or directory
make: **\* [eeprom.bin] Error 1

Compiling firmware for Taranis breaks during the build of the bootloader:
Include/core_cm3.h:126:97: fatal error: core_cmInstr.h: No such file or directory
 #include "core_cmInstr.h"                /_!< Core Instruction Access */
compilation terminated.
make[1]: *_\* [usbd_ioreq.o] Error 1
make[1]: Leaving directory `c:/src/github/opentx/radio/src/bootloader'
make: **\* [bootloader/bootloader_ramBoot.bin] Error 2

Compiling firmware for 9XRPRO breaks with an error on wget:
Fetching Mike's bootloader...
wget https://ersky9x.googlecode.com/svn/trunk/src/bootloader/bootflash8.lbm
https://ersky9x.googlecode.com/svn/trunk/src/bootloader/bootflash8.lbm: Unknown/
unsupported protocol.
make: **\* [bootloader.lbm] Error 1

**Comment by Spainman** [comment]
So what is the essence? Is Windows simply unsupported or are there just unsolved problems that nobody had time to sort out? 

I really would like to get involved and try to implement some ideas instead of just making uneducated suggestions knowing nothing about the OpenTx innards. Of course I could just boot up a VM but I know that once I start it will be a long-term thing so I would really prefer to run the tool my 'native' platform with my favourite and familiar editors and surroundings.

Does it make sense if I spend time trying to get things running on Win or have others already tried and found it to be impossible due to incircumventable third party incompatibilities / issues with Windows?

**Comment by kilrah** [comment]
As far as I remember libfox does not build on windows, but I don't know why and/or whether it's fixable or not. Or who knows maybe it does now since last we looked was probably a couple of years ago...

Of course it would be good to have it, but I can't really help you to get there.

**Comment by Spainman** [comment]
Thank you - knowing that there is chance already helps. I'm going to set everything up on Linux first to have a working environment for comparison with windows. 
Are the Linux build instructions still up to date (specially for the fw)? The page was last updated nearly a year ago and I'm wondering if certain reqs like gcc 4.7 are still current. It would appreciate it if you could have a quick look in the wiki and confirm that things still are what is used on the build server.

**Comment by Spainman** [comment]
Anybody able to answer my question from 2 days ago? Are the linux build instructions up to date?

**Comment by griebd** [comment]
they should be, I compile my companion and firmware the same way since I started compiling it myself and I followed the guide on the first time! :wink:
