### ISSUE TITLE
global variables in curves

### ISSUE THREAD

**Issue by andras** [opentx/opentx#1433]
Maybe this has been discussed before, but one important piece of functionality appears to be missing: curves are static, you cannot set individual Y values to GVs or anything else that can change.  I believe that such functionality would be very useful, for example when trying to optimize a mixer curve in flight (with, say, S1 on the Taranis for adjusting one point of a curve).  I believe, but might be wrong, that the better Multiplex radios offer an equivalent option.

RFC.

**Comment by mrabault** [comment]
What is the status of this feature ? Even allowing to use GVARs as curve coordinates would make programming way more expressive.

For instance, let's imagine you want to tune deadbands for snapflaps, for instance. Currently,  you'd need a Lua script (like [this](http://www.rc-soar.com/opentx/lua/snap202A.txt)). However, providing this feature would mean that you only would have to set the curve mode to Custom and then assign the x-value of a point to a GVAR, and finally use a custom function to tune that GVAR using a pot. It's pretty clear to me how useful this would be, even though it'd probably require an EEPROM format update.

**Comment by pandjarov** [comment]
I wonder why this is marked as stale and closed with zero dev activity. This is great feature that can be useful in so many ways. For example with a variable curve, you can adjust your throttle to work from -80 to -80 in its lowest point to +100 setting the idle speed of your gas engine in a great way. I hope you reconsider and add this functionality. Allowing GV as values for the curve would be more than enough since that would allow so many use cases.

**Comment by Eldenroot** [comment]
Try EdgeTX :)
