### ISSUE TITLE
More user friendly access to setting pages on Taranis

### ISSUE THREAD

**Issue by pindeslandes** [opentx/opentx#1608]
If you are the kind of user who doesn’t change his settings every day, it can be hard to remember the shortest way to jump from a setting page to another.
When you are not sure, you would probably choose to explore only one direction until you find the page you want (let’s say down because PAGE-short is easier than PAGE-long), which might need to press twelve time the key if the page finally revealed to be the next up. It’s a long journey. 
And even if you remember that GLOBAL VARIABLES page is #9/13 and FLIGHT MODES is #4/13, you still have to deal with this deeply disturbing question: “Would I better long press PAGE five times or short press PAGE eight times?”
OK, I am pushing it a little but you get the idea.

1) It would be nice if, when you press MENU (short or long) from the main view, you got not directly the first page of settings (model selection or radio setup) but an intermediate layer that displays the list of the pages. Then you could easily and rapidly select the page you want with +/- keys and ENTER (in addition, + key is more convenient than PAGE-long).
Also, it would be more consistent with what is generally understood by ‘menu’ (i.e. you expect a list of items, not the first item of the list).
Once on the page you want, of course, you wouldn’t lose the possibility to jump to an adjacent page on pressing PAGE-short or long, while pressing EXIT would bring you back to this new menu screen (and EXIT again to get back to the main view).

2) I guess the reason why it is done like it is done today is to give a direct access to MODEL SELECTION because it is supposed to be the most often used setting (and may be the same logic has been symmetrically applied on the radio setting side). In my proposal, you need one more key press to access this page. No big deal but I would suggest that, in order not to lose this direct access from the main view, another key be used. May be EXIT to go to MODEL SELECTION would make sense (and EXIT-long for RADIO SETUP to keep the symmetry although I am not sure that such a direct access to RADIO SETUP is so useful).

**Comment by mhotar** [comment]
![modelset_mixer kopie](https://cloud.githubusercontent.com/assets/6114100/5603810/07ce74cc-9397-11e4-9290-44cc548bbb4c.png)

Not all icons are done, but some progress here.

**Comment by mhotar** [comment]
Finally I have finished icon-set for taranis, here it is:
![default_background](https://cloud.githubusercontent.com/assets/6114100/5891502/821fe1a8-a499-11e4-8195-7d37ed5d07a6.png)
I am open to any comments and suggestions. I am looking forward to see it on the real LCD :)

**Comment by Excaliburst** [comment]
Looking great!

Well the best way to find out if they actually work as intended is to see what people 'interpret' them as. 

So that is what I am going to do.
Top line: 
1. Setup/configuration
2. Storage
3. I am not familiar with this icon
4. User config
5. Information
6. Contrast/colour adjustment of screen
7. Something with pots and switches - I have no clue
8. A chip - might signal hmm bummer I have no clue
9. A HDD, might mean check number of models etc.

Second line:
1. Folder - meaning browsing the SD card structure on Tx.
2. Config/setup
3. Model (setup)
4. ???
5. Input   ---
6. Mixer     |   These 3 icons look really nice, and are easy to discern.
7. Servo ---
8. Looks like a shoestring - I have no idea?
9. Out/In normally used reverse I/O. Could mean the network (WiFi, Bluetooth)
10. The lightning must mean network or charging settings - a little ambiguous.
11. An eye with line of sight - what could this represent??
12. A pot. What does that represent.
13. X must mean OS options.

Please comment about how close I am to your meaning of each icon, and what all the icons mean. Then it is easier to actually give you feedback.

Also looking forward to seeing the screen of the Horus. Ups I just saw that this was for the Taranis. Can that be true? The screen proportions are more like the Horus, and the Taranis has no colour. Must be a mistake. Please enlighten us!?

Great work - thanks

**Comment by mhotar** [comment]
Hello Excaliburst, thanks for your answer.

 >Well the best way to find out if they actually work as intended is to see what people 'interpret' them as.

Great idea, lets walk trough it then.

>So that is what I am going to do.
Top line:
1.Setup/configuration

=Radio setup
>2.Storage

=File browser
>3.I am not familiar with this icon*

=Global functions, lightning represents power, some kind of action here. Broken circle around means its global state, it is similar like Functions icon below.
> 4.User config

Well, there are two persons on the icon, it represents their relation, one is white, second is black.
=Trainer setup
>5.Information
6.Contrast/colour adjustment of screen

=Switch test
>7.Something with pots and switches - I have no clue

=Analog test
>8.A chip - might signal hmm bummer I have no clue

=Hardware configuration
>9.A HDD, might mean check number of models etc.

=Calibration, icon represents pointing to the center of the circle
>Second line:
1.Folder - meaning browsing the SD card structure on Tx.

=Model selection
>2.Config/setup

=Model setup
>3.Model (setup)

=Heli setup
>4.???

=Flight modes
>5.Input ---
6.Mixer | These 3 icons look really nice, and are easy to discern.
7.Servo ---

>8.Looks like a shoestring - I have no idea?

=Curves
>9.Out/In normally used reverse I/O. Could mean the network (WiFi, Bluetooth)

=Logical switches
>10.The lightning must mean network or charging settings - a little ambiguous.

=Special functions
>11.An eye with line of sight - what could this represent??

=Telemetry
>12.A pot. What does that represent.

=Custom scripts - this is regular LUA logo
>13.X must mean OS options.

=Global variables
>Please comment about how close I am to your meaning of each icon, and what all the icons mean. Then it is easier to actually give you feedback.

So, you were not far sometimes, I am happy there will be textual name too.

>Also looking forward to seeing the screen of the Horus. Ups I just saw that this was for the Taranis. Can that be true? The screen proportions are more like the Horus, and the Taranis has no colour. Must be a mistake. Please enlighten us!?

This is sort of presentation only, only icons are related here.

**Comment by Excaliburst** [comment]
Thanks for clearing the uncertainty up with the icons. With their meanings known, I think your icons are really well thought out and beatifully crafted.

I only have comments about a few icons:
- Global Functions - I think you should use a globe (Earth) icon to indicate Global.
- The one for calibration is not good. It really resemble a HDD icon. May I suggest insted of an arrow you try to draw a bullet-hole, so that it is clear that we are talking about a shooting target with shots off to the side.. Just an idea
- Model Selection - Would be more obvious with actual models in icon, maybe a glider + heli icon.
- Model Setup - Would be more obvious with a model behind the wrench.
Logical Switches - Maybe use LS instead of OI. Would then be obvious to an OpenTx user.
Special Funktions - Ambiguous, not very describing/obvious. No suggestions though. Sorry.
- Global Variables - Would be much more obvious with same globe icon from Global Functions but with the X lingering over it. The box does not do good things.

I like the rest of them a lot. 

Thanks

**Comment by mhotar** [comment]
Thanks for your feedback Excaliburst.
I do agree with most of your comments and I will try to alter these icons.
The biggest issue here is space/resolution limitation I have, It all should fit to 23x23pixels, so not much space for meaningful details.

**Comment by mhotar** [comment]
Hello, @Excaliburst
can you walk through these icons and let me know how do you fill it?

![icons21](https://cloud.githubusercontent.com/assets/6114100/5920393/8d266a28-a63c-11e4-8b9f-d35c751140cf.png)

**Comment by Excaliburst** [comment]
Hmm.

Model Selection is excellent
The 2 icons after Sim card are not very good. We need more information...
Calibration is OK. Not great.
Model Config (2. line 1. icon) is not very descriptive
After curves with the balance. Not very descriptive
And the next one either.

Sorry most of them are not as good as in your first attempt.

But this is only my opinion - Cheers!


Morten Enevoldsen

Tlf: +45 4098 0898

2015-01-27 15:55 GMT+01:00 Martin Hotar <notifications@github.com>:

**Comment by mhotar** [comment]
Ok thanks,
I have sorted them a little more. I did my best for now, we can change them later when some better idea come up.
![icons21](https://cloud.githubusercontent.com/assets/6114100/5929045/7d7e7b6c-a680-11e4-99e4-4f45e5283e18.png)

**Comment by bsongis** [comment]
Those icons are really nice!

**Comment by bsongis** [comment]
Comments about my last change in the navigation? It feels bad to me (but perhaps because I am too much used to the previous navigation system). Please tell-me if I miss something! At least it will need a compilation option.

**Comment by mhotar** [comment]
Yes, It is something different than we had before.
![snapshot_10](https://cloud.githubusercontent.com/assets/6114100/5987491/410ee8fc-a92c-11e4-985d-8b2347a367d5.png)
![snapshot_11](https://cloud.githubusercontent.com/assets/6114100/5987493/46948f98-a92c-11e4-9e74-db4ead4ade56.png)
You did great job again, I hope it will be helpful for newcomers. But i am positively biased, so better to wait for some other`s opinion, or publish it on the rcforums.
I would only change the controls a little.
[Menu] opens icon-menu, same as you have now
[MenuLong] opens last used page in model-setup directly
[Page/Page Long] walks through menu items

Did you test it on the real LCD? How does it look?

**Comment by mhotar** [comment]
Well, I forgot it already has history, it pre-selects last used items.
So the [MenuLong] is not necessary.

**Comment by Spainman** [comment]
Haven't tried the current code, so I'm just guessing from the previous comment how it might work now.
But I would suggest to use
- (+)/(-) for navigation through the items in the menu 
- (ENT) for selection/confirmation 
- Page/Page long the way it always was (no menu bar appears, direct movement through pages)

Long press for navigation through visible icons would feel annoying. +/- would be intuitive and fast.

**Comment by bsongis** [comment]
@Spainman Please give a try and update your comment, it doesn't help too much ;)

**Comment by jtaylor2** [comment]
I find it a little harder to use. For example, old way, one long press menu would take me to radio setup and I could page through the screens .  Now it takes short press menu and, depending on what my last selection was,  multiple presses of + or - to get to the radio setup icon, press enter, and then I still need to page through the screens.  Of course I'm used to the old navigation and have lived in a command line for 50 years so I'm more impressed with efficiency and simplicity than aesthetics. I'm also not sure it actually solves the original complaint of this issue, which was that you needed to remember where the screens were, or page through them to find the one you needed.  This way you either need to remember what the icons represent or cycle through them with the +- keys to read the text and then press enter to actually go there (instead of already being there the old way).

I can see the advantage of having a gui and icons on a touch screen where you can directly select the icon, or a system with a mouse and hover over help, but I don't really see the advantage on a key driven interface (particularly one without enough screen resolution to have text labels under the icons).  To me it seems a little less efficient than a drop down list with the most recently used item selected.

It seems to work, and is usable so it's just a matter of getting used to it.  However, unless it makes it harder to maintain, a compile option to keep the old interface would be nice, especially if the new one consumes more resources.

Jim

**Comment by mhotar** [comment]
Here is still the first idea to consider. It does not change controls, and keeps all menus the same, only adds icons, so you can see how far is the page you are looking for. (Yo have to remember the icon meaning off course)
![snapshot_12](https://cloud.githubusercontent.com/assets/6114100/5990151/03cba3c2-a9a4-11e4-9945-c6cbc79c06e4.png)

[Menu/MenuLong] opens the model-setup/radio-setup, the same as usual
[Page/PageLong] walks through pages with icons displayed on the top and four lines of content displayed as well. Configurable timeout or [+/-/Enter] closes the icons and shifts the page back.
Timeout set to zero can disable icons completely.

**Comment by Sacre100** [comment]
I hope that there will be an option to show or hide these icons.

**Comment by jtaylor2** [comment]
>Here is still the first idea to consider. It does not change controls, and keeps all menus the same, >only adds icons, so you can see how far is the page you are looking for. (Yo have to remember the >icon meaning off course)

The icons are very nice, but to me they don't add anything to this type of interface and actually make it less efficient.  As I said it would be different with a touch screen or mouse.  However, if it worked the way you suggest it would be better than the way it is working now (which I'm sure is just a first start/demo).

The existing page numbers (5/12) tell me where I am in the pages, and to me it's actually easier to remember the order of the pages than to remember the meaning of icons.  You still have to walk the pages to get to the page you want (the icons would be nice with a touch screen), and if you aren't sure which page you are looking for you have less content visible on the pages to help you find it.  And once there you either have to wait for the timeout or hit another key to dismiss the icons so you can use it.

I know everybody seems to want a gui and icons these days (even if the interface isn't designed for it) and thinks anything without icons is old fashioned .  If it worked the way mhotar suggests (not change the controls and Page/PageLong walk through pages the way it does now) it would be usable by everyone, but I still think a NOGUI compile option (selectable in companion) would be a good idea for those of us that prefer efficiency over bling.

Jim

**Comment by pindeslandes** [comment]
:+1: @jtaylor2

**Comment by franck76** [comment]
I like these icons a lot but would also prefer it as an option

As I see, there is enough room for 8 icons on the top line : 
General radio settings involves 8 pages/icons and Model setting menu 13 icons, depending on whether you choose Heli option or not.

So I would suggest : 
[Menu] displays 1 view with the following icons : Radio setting, Model setting and other useful icons such as (Model selection, SD card, Telemetry, Custom script, Trainer, Information…)

If you select a menu with more than 8 screens, for instance Model Setting menu,  then display the first 8 icons in one screen and  the next 5 icons in another screen that you select with [page]. And use [+/-] to walk through each page with icons

That would save a certain number of clicks in my opinion
