### ISSUE TITLE
T-Trim doesn't follow the throttle trim when you cross trims

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#170]
_From [joaoalve...@googlemail.com](https://code.google.com/u/107758819364615868605/) on October 28, 2013 21:10:23_

Which board (stock / gruvin9x / sky9x / Taranis) are you using? All boards I suppose..

Swap the throttle and elevator trims.. Ele trim will affect throttle and vice-versa

Now activate T-Trim.
It will not follow the throttle trim and will affect the elevator trim..

_Original issue: http://code.google.com/p/opentx/issues/detail?id=171_

**Comment by mcddd** [comment]
I'm a fan of crossed trims and would really like to see this problem solved.  For electric models the crossed trims work great since the T-Trim function isn't needed. But for gas/glow engines where the throttle trim is only effective at idle, selecting the T-Trim function doesn't follow the selected trim input for the throttle channel. Instead the T-Trim function always affects the THR trim regardless of which trim input device is assigned to the throttle channel. The result is that when cross trims are selected the T-Trim function ends up affecting the elevator channel trim instead of the throttle channel trim.

**Comment by projectkk2glider** [comment]
Instant trim is also affected, see #3927

**Comment by AloftHobbies** [comment]
@bsongis - Do you think you can look into this issue a little closer for the next release. These gas guys have been waiting a while to see this small bug fixed. I have a few different folks asking if I can help get this resolved. Thank you very much!!
