### ISSUE TITLE
Wrong joystick channel mapping.

### ISSUE THREAD

**Issue by Sacre100** [opentx/opentx#1732]
Version 2.0.12.

Using the USB cable, the mapping of the channel is wrong : 
Ch1 >> Ch1       -  OK
Ch2 >> Ch2       -  OK
Ch3 >> Ch3       -  OK
Ch4 >> Ch6       -  WRONG (4 and 6 are inverted)
Ch5 >> nothing  -  LOST
Ch6 >> Ch4       -  WRONG (4 and 6 are inverted)
Ch7 >> nothing  -  LOST
Ch8 >> Ch5       -  WRONG

**Comment by bsongis** [comment]
I don't know this part of the code. I see this:
if (axis>=0 && axis<=8) 
So, 9 channels?

**Comment by bsongis** [comment]
Oh but ...
int jsmap[8];
At least there is a bug

**Comment by bsongis** [comment]
The Joystick object can send signals:
-  axisValueChanged
-  buttonValueChanged
-  hatValueChanged

Only axisValueChanged is catched, I am afraid in your case one of the 2 other signals is needed.

**Comment by bsongis** [comment]
Out of curiosity, what is a hat? Google translate doesn't help ;)

**Comment by projectkk2glider** [comment]
http://en.wikipedia.org/wiki/Joystick#Hat_switch

**Comment by davxlw** [comment]
@bsongis,
> Out of curiosity, what is a hat? Google translate doesn't help ;)

![aviatorlogitechjse-orig](https://cloud.githubusercontent.com/assets/7569433/5685801/4146c42e-983e-11e4-98c5-f24aeb2278eb.jpg)

**Comment by jtaylor2** [comment]
I took a look at this today with the thought of trying to fix it.  Verified that it works correctly on self compiled next on OpenSUSE 13.2 Linux and fails as reported on Windows 7 with both downloaded 2.0.15 and self compiled next compiled with Cygwin.

Discovered that on Windows  SDL_JoystickNumAxes(joystick); in joystick.c was returning 6 axes instead of 8.

Looking at the source for SDL-1.2.15/src/joystick/win32/SDL_mmjoystick.c found this statement:

#define MAX_AXES 6 /* each joystick can have up to 6 axes */

So it looks like SDL only supports 6 axes on Windows.  Took a look at SDL2-2.0.3 (even though Companion won't compile with SDL2) and it has the same limit on Windows.  Thought about trying to recompile SDL with MAX_AXES 8, but it looks like a lot is hard coded to expect 6.  At this point it's beyond me, so just documenting what I found.

Jim

**Comment by projectkk2glider** [comment]
@jtaylor2 Looks like we must be sure to use only 6 axes on Windows. There is no way around it. 

There is another related problem. The Joystick class initializes SDL each time it's constructor is callled like this:
```
SDL_Init(SDL_INIT_JOYSTICK)
```

I believe the `SDL_Init()` should be called only once at the application start. We must also initialize Audio part of SDL now, that the simulator uses SDL to produce sounds. So we should call (somewhere at app start):
```
SDL_Init(SDL_INIT_JOYSTICK | SDL_INIT_AUDIO)
```

**Comment by projectkk2glider** [comment]
As far as I am concerned this issue is now fixed.

The Windows version of SDL 1.2 library is limited to 6 analog axes. The only possible work-around would be to define two more axes as a hat switch/joystick. But that one has only 8 bit resolution. This would require changes both in radio firmware (USB joystick descriptor) and in Companion. In my opinion it is not worth the effort.

**Comment by bsongis** [comment]
I compiled a new release with your fix included, so it's already available for tests!
