### ISSUE TITLE
Yaw, Pitch & Roll in telemetry

### ISSUE THREAD

**Issue by Sacre100** [opentx/opentx#1777]
It would be great to have these 3 additional fields in addition to AccX, AccY and AccZ.

**Comment by teckel12** [comment]
@Sacre100 FYI, you can calculate pitch and roll using the already available AccX, AccY, AccZ to create an artificial horizon.  I'm doing it to create a telemetry screen in Lua for INAV that simulates a glass cockpit:

![inavqx7pilot](https://user-images.githubusercontent.com/2592128/43601702-d66e5ffc-965b-11e8-8c3a-4d8a07f1efcd.png)&nbsp;&nbsp;![inavx9dpilot](https://user-images.githubusercontent.com/2592128/43601703-d681baa2-965b-11e8-906b-178077f6e02c.png)

More info: https://github.com/iNavFlight/LuaTelemetry/wiki

Code snippet from Lua Telemetry that calculates pitch/roll:  
```c++
local pitch = 90 - math.deg(math.atan2(data.accx * (data.accz >= 0 and -1 or 1), math.sqrt(data.accy * data.accy + data.accz * data.accz)))
local roll = 90 - math.deg(math.atan2(data.accy * (data.accz >= 0 and 1 or -1), math.sqrt(data.accx * data.accx + data.accz * data.accz)))
```

**Comment by kilrah** [comment]
This works on the ground but in flight dynamic accelerations will skew it completely.

**Comment by teckel12** [comment]
@kilrah If there's better math, I'd love to incorporate it.

**Comment by mpaperno** [comment]
You cannot get a reliable absolute position from an accelerometer alone. You need a gyro and an accel. to correct for each other (at minimum... though a fancy filter to correct for errors doesn't hurt either).  The examples you posted are getting orientation data from the flight controller itself (which has the above-mentioned components), not from raw sensor inputs.

**Comment by teckel12** [comment]
@mpaperno I've flown quite a bit with the above logic and it seems quite accurate. But, it was with a quad which is mostly a stationary craft. On the bench, it's extremely accurate. I'm not doing yaw at all, only roll and pitch.

But I'll concede to your experience and expertise. And it sounds like to make this accurate I should replace the accelerometer telemetry with yaw, roll and pitch. I can easily do this with an option in the FC which will send this data to the transmitter instead.

Doing this will also make it easier to calculate bearing vs flight direction vectors, which I've been working on today (and the reason this old issue was raised from the dead).

**Comment by mpaperno** [comment]
Yes if you can get the data from the flight controller itself, by all means use it. Not only will it be more accurate, but it will also be the FCs "reality" vs. yet another "reality" created by the acc sensor calculations in the Lua script.  Plus the only way to get an actual compass heading is to get a magnetometer involved in there somewhere...  plus altitude/etc.

Though to be honest I've never really understood the need for a PFD on the radio... you can't actually fly using it (too laggy/etc), tiny/low rez screen, and typically not near to the line of sight to the craft.  To really fly "IFR" one needs a real ground station with a fast dedicated telemetry link.

I also don't understand why this issue is still open... custom sensors in OTX are "old news" now.

**Comment by teckel12** [comment]
@mpaperno The compass heading does come from the FC already. As does the altitude and the rest. The only thing that uses the accelerometer is the artificial horizon, maybe that's why the accuracy is higher than expected?

A glass cockpit view was requested, I guess from non-FPV pilots.  Updates on opentx are 5fps, which seem good enough for my beta testers.

**Comment by mpaperno** [comment]
Well it does look sexy and if you only look at it while setting up it doesn't really matter what it shows.  :-)

And yes on a dynamically stable object the acc. estimation could be reasonable, like, as you said, on a hovering MR which is already stabilized by the FC against external factors like wind and sensor drift.  Plus of course an "acceptable" error rate is relative.

But you don't have to take our word for it... consider the fact that no MR (that I know of) flies with acc-only (gyo-only, yes). That is because the errors would build up and you'd very soon be fighting the stabilization instead of being assisted by it (it's a fun experiment in a simulator ;-) ).  And also that any self-respecting IMU board on the market has at least acc and gyo, and probably some kind of basic fusion algorithm already built-in.

**Comment by teckel12** [comment]
@mpaperno So really, the accelerometer telemetry data is pointless to send to the transmitter.  Instead, we should be sending Yaw, Pitch & Roll in it's place, as every FC is calculating this anyway.

So at least in INAV, I plan on replacing: AccX -> Pitch, AccY -> Roll, and AccZ -> Yaw.  I'll provide a switch for backward compatibility if anyone is using accelerometer telemetry for whatever reason.

BTW, thanks a lot for pointing me in this direction.  It's greatly appreciated!

**Comment by kilrah** [comment]
FrSky used to sell an accelerometer sensor and that's what it came from.
This issue was precisely about choosing new IDs so as not to misuse the existing ones.

**Comment by teckel12** [comment]
@kilrah Should I use particular IDs for roll and pitch? Yaw was already be sent as heading, so I was going to use the IDs 0x0850 for pitch and 0x0860 for roll to follow heading which is already 0x0840.
