### ISSUE TITLE
Swash input enhancement to add explicit aileron and elevator channels

### ISSUE THREAD

**Issue by ArchmageAU** [opentx/opentx#1878]
Currently for swash mixing, Aileron and Elevator values are taken from last processed input that draws it's value from elevator and aileron stick inputs.

Would it be possible to expose and option to select the Aileron and Elevator input values to the swash mix (instead of the current auto-select).

**Comment by jermoo** [comment]
We need to move swash mixing from Inputs to mixers to fix a number of issues related to Flybar heli, including the inability to use a buddy box without the student radio performing mixing. The student radio should ONLY need to input PPM channel data. This "issue" with buddy boxing was reported to me and has not been verified by me.

**Comment by projectkk2glider** [comment]
As far as I understand the swash mixing is only needed on "old style" choppers that have only three cyclic servos driven directly by the receiver.

On flybar systems the mixing is done by the on-board controller which expects simple Aileron, Elevator and collective signals. In such case you should have no problem with your trainer setup. 

Correct me if I am wrong and provide further details.

**Comment by bsongis** [comment]
It should work in the nightly builds.

**Comment by jermoo** [comment]
your second paragraph; I believe you meant flybarless controllers. The issue is that most of us buddy box new pilots on flybarred models. Currently we can't use the buddy box feature of the Taranis whenever the Swash menu is used without doing a mix setup on the student controller which should not be necessary and over complicates a very simple thing. If it would be easier to fix buddy boxing to work regardless of where the swash is mixed that may be a better option. I'm just not sure how we'd do it without looking at the code as the Inputs are the first place I see for use to do the inputs. I have to look at he code more, I'm still learning.
Jer

**Comment by bsongis** [comment]
No, the buddy box should work as you describe, would you do a test to check we are right? If no, feel free to reopen the issue!
