### ISSUE TITLE
Security Password Feature

### ISSUE THREAD

**Issue by JSGordon** [opentx/opentx#1890]
Would like to see ability to add a security password to protect radio and model setting.
In a commercial application it would be nice to be able to lock down setting to prevent accidental or otherwise modification to settings.

**Comment by jace26** [comment]
I'm digging this up since I don't see this elsewhere. I agree version control for commercial applications is very important. I would like to hide configurations behind passwords for the radio and models. It doesn't look like this is an option currently:
https://opentx.gitbooks.io/manual-for-opentx-2-2/radio_options.html
nor does it look like it was an option back on 2.1
https://github.com/opentx/opentx/wiki/OpenTX-Compilation-Options
