### ISSUE TITLE
SD card file manager

### ISSUE THREAD

**Issue by pindeslandes** [opentx/opentx#1924]
On the Taranis, there are some functions that can be automatically triggered if the appropriate files are in the appropriate folder on the SD card (play audio files for flight modes and switch positions, LUA scripts). But the only modification you can do on a file with the transmitter is deleting it, whereas a computer is still needed to do anything else. Not very convenient when you are at the field, willing to do any other modification than disabling such a function with no possible way to enable it back again.
To get some control on these functions, it may be useful if the radio were able to do such basic operations as:
- temporary deactivating a file without the need of deleting it (by moving it elsewhere or giving it another name, for instance, or even with a recycle bin),
- copying a file from a model to another,
- other?

So it would be nice to have a simple file manager that could just:
- copy / cut / paste a file,
- rename a file,
- and maybe create a new folder (that last one would be the icing on the cake).

**Comment by bsongis** [comment]
Still needed a way to create a directory

**Comment by ptowalski** [comment]
I'm new to OpenTX (opentx-x9d+, 2.2.0, 85863359), had the following issue with the file manager and wanted to drop a short bug report:
- During rename it is possible to insert invalid characters by simultaneously pressing the (+) and (-) keys (shortcut).
- Durning rename it's not posible to shorten a file name for example rename "ab.wav" to "a.wav" because the "empty" character cannot be select. It is possible to modify the current empty character with the (+) button but it is not possible to select it back with the (-) button.
- If i copy a file it is not possible to paste it into an empty folder because the context menu does not appear.

**Comment by lshems** [comment]
on Xlite it seems impossible to store the chnaged filename. What key events are neccesary to save the new filename??
