### ISSUE TITLE
S3 pot change selection by itself - Taranis Plus Tx

### ISSUE THREAD

**Issue by gelatmi1** [opentx/opentx#1943]
On Taranis Plus Tx, sometime the S3 pot after has been selected as 'Multipos switch' come back by itself to 'NONE' !!!

**Comment by rcorbari** [comment]
Hi, my S3 switch has set no "none" in radio HW settings, just after a calibration. I tried to calibrate the S3 before anything else but since it's not visible as hardware, the slide does not appear on the display and it's not recognised.
What I can do?
It used to work until this last calibration, soldering is OK.

**Comment by kilrah** [comment]
What is actually connected to S3?
If 6-pos switch, set it correctly then calibrate, try a couple of times moving the switch slowly.

**Comment by rcorbari** [comment]
Sorry,

a 6 position encoder purchased from Helibatics is connected to the S3 port. I use it for the Pixhawk flight modes, and it used to work.

The problem is that I cannot calibrate it because it's not visible in the radio hardware page.

Bootloader 2.0.15
Craft and Theory firmware for Arducopter 3.3.3.

**Comment by kilrah** [comment]
What OpenTX and Taranis version...?

**Comment by rcorbari** [comment]
2.1.8
EEPROM 217
Taranis X9D Plus purchased in early 2015 (should be a 2014)

**Comment by kilrah** [comment]
There is no way it could just have disappeared from the menu... Are you sure it's not renamed?

**Comment by rcorbari** [comment]
It is reported as "none", with the previous Taranis version it was possible to activate the S3 connection, now it's not possible.
![img_0720](https://cloud.githubusercontent.com/assets/318975/17463697/f16d6774-5ccb-11e6-8378-8a9ad965006c.JPG)
![img_0721](https://cloud.githubusercontent.com/assets/318975/17463698/f4d39974-5ccb-11e6-9020-27e99cc6ebfb.JPG)

**Comment by kilrah** [comment]
That "None" is there to be edited and set to what applies to your particular case....

**Comment by rcorbari** [comment]
I cannot select that field like I used to be able before
