### ISSUE TITLE
[Bug][Companion 2.0.15]Various bug on model wizzard

### ISSUE THREAD

**Issue by Sacre100** [opentx/opentx#2091]
Model wizzard allows only to select Channel 1 to 8 on Taranis even if Channel 1 to 32 are available.

![bugwizard3](https://cloud.githubusercontent.com/assets/8712977/6250281/14249340-b78d-11e4-92ba-7d367d7e68b6.png)

On "Tail" window, when Channel 1 to 8 are used for other control, the dropdown propose only Channel 1 and "Next" button has no effect (only "Prev" or "Cancel" buttons have an effect)

![bugwizard1](https://cloud.githubusercontent.com/assets/8712977/6250517/b0269008-b78e-11e4-8922-9b3b759f4595.png)

**Comment by griebd** [comment]
We have two different things here....

1. A bug: when no channel left to be used on 'Tail', or anywhere in the wizard, a error message should be shown. (I will look at that... :wink:)

2. A project choice to be made: keep the actual wizard, made for a 8 channel (maximum) model. Or change the wizard so that the user chooses the number of channels for the model.
I simple don't use the wizard and I think (made wrongly) that if you need more than 8 channels you don't need a wizard... :wink:
Anyway, if it's decided to do the change, I'll look at it too.

**Comment by kilrah** [comment]
> I think that if you need more than 8 channels you don't need a wizard... :wink:

Same here, nearly closed the issue straight away because of that. The wizard has been done as "basic handholding for the first steps", so you can see at how it did what you told it to... if you need everything you've already outgrown it.

**Comment by griebd** [comment]
Did a fix to show a message on "tail" page when there is only one channel left.
As for the number of channels, I still think it's not necessary. If you need "that power", OpenTX IS for you!!! The wizard is only a introduction to it's "power", as pointed by @kilrah.

**Comment by griebd** [comment]
Already merged for 2.0.16.
