### ISSUE TITLE
2.0.17 Mixermon

### ISSUE THREAD

**Issue by MIKE-DAILEY** [opentx/opentx#2258]
Mixermon is working on my Taranis Plus fine, but is not working in Companion simulator.  Not sure if I'm doing something wrong.  In the simulator, at the monitor screen, when I click ENT the monitor screen does not change to Mixer monitor. 

Mike

**Comment by bsongis** [comment]
In 2.0.x the Companion simulator uses only standard options, not the options the user chooses.

**Comment by kilrah** [comment]
There's no reason not to include it in the simu though, is there?

**Comment by LapinFou** [comment]
I think there is a very good reason. I guess most of the pilots will develop their complex program under Companion. Having the MIXERS MONITOR would be very nice in order to debug complex mathematical operations. Specially when the mix result is going over 100% !
An example to illustrate how useful it is: with the "mixers monitor" you will see and understand why the channel (with a 'slow' parameter) that you are programming takes some time to move. You will see that you max channel is going over 100% and reach 200%. Since you got a "slow" parameter, your channel must recover from +200% to +100% before you actually see any movement on the "servos monitor".
Without the "mixer monitor", it can be quite difficult to understand and correct the problem.
So, I think, this option should also be implemented in Companion.
As I said, I'm always programming my models from my PC. So, to me, this option is even more useful under Companion as in the Taranis itself.

**Comment by kilrah** [comment]
I said no reason NOT to include it. And it's in now as you can see with the 2 commits.

**Comment by LapinFou** [comment]
Oups !!! Sorry kilrah, I misread your comment.
My apologize.
Will you release soon the 2.0.18, in order to be align with the firmware?

**Comment by pindeslandes** [comment]
I know this is closed but wouldn’t it be more convenient if Companion could show the mixers monitor in some tabs here, as for outputs?
![onglet](https://cloud.githubusercontent.com/assets/8396899/9091002/fa9b5946-3b9d-11e5-91d2-6d5786e5dc64.PNG)

**Comment by LapinFou** [comment]
Yes !!! I love this idea !
:+1:

**Comment by projectkk2glider** [comment]
Create a new issue or this will get forgotten.

**Comment by pindeslandes** [comment]
Done!

**Comment by mpaperno** [comment]
This seems to have gotten lost somewhere along the way, `MIXERS_MONITOR` is no longer defined by default for Taranis simu/libsimulator builds.  We could force it in simu/CMakeLists but of course then there's no way to build simu w/out it... but maybe that doesn't matter?

**Comment by kilrah** [comment]
The defaults are not in the code, but in the release build scripts on the server. Before 2.2.0 release we'll have to do a little rundown of the useful options to include by default for each variant. Since it changes during development we don't bother doing that before it's final.

**Comment by mpaperno** [comment]
Sounds good, yes, best to handle it in the build scripts with the rest of the defaults.
