### ISSUE TITLE
wrong units for logical switch conditions

### ISSUE THREAD

**Issue by diablol** [opentx/opentx#2285]
please have a look at the logical switches for
a) decimal value for minV
b) wrong unit for alt
thanks

here my eepe, 
https://drive.google.com/file/d/0B-imnPmcHH_waTd6cmhKOVY1ams/view?usp=sharing

**Comment by kilrah** [comment]
Should be fixed. BTW my mistake as I talked of "eepe", but for future issues please post the untouched EEPROM.BIN file directly from the radio instead of a .eepe from companion. For example in this case the bugs in companion caused the .eepe file to be "corrupted" and thus unuseable to test the fix.
