### ISSUE TITLE
Taranis Plus S2 pot problem

### ISSUE THREAD

**Issue by PoriG** [opentx/opentx#2364]
Hi guys!

I have the latest revision Taranis Plus with the latest software from FrSky. When I try to set my S2 pot as an input source by turning it while the source option is highlighted, the transmitter sometimes detects it as S3. This mostly happens close to the center point of S2. In my settings S2 is set as pot with detent and S3 as none. Also calibrated the pot multiple times. Here is a video someone posted on youtube about this behaviour: http://youtu.be/NeWSy73GsEs
Anyone has any idea why this could be happening? Otherwise the pot works fine when I select it as source manually. S3 is not installed in my radio.

Thanks for any info!

**Comment by projectkk2glider** [comment]
@PoriG are you willing to test the fix for this?

If yes, please backup your radio (models and firmware) and then flash this file http://jenkins.open-tx.org/nightly-20/2015_06_17/opentx-taranis-plus.bin

The flash file posted above has some default options which might be different from your selection. Ignore that and focus on S3 issue and report back.

We also need somebody else with Taranis Plus that has installed S3 pot to test if it still working.

**Comment by PoriG** [comment]
Sure! I will test it this afternoon. I will report back.
