### ISSUE TITLE
Vario only showing positive values

### ISSUE THREAD

**Issue by helicop** [opentx/opentx#2382]
As title. Taranis Plus. Nightly 23/06/2015. Frsky D4R-11 and OpenXVario. In sensor page (13/13) only positive values are shown for Vspd.

**Comment by projectkk2glider** [comment]
My solution in https://github.com/opentx/opentx/commit/a88cace88855aed107dd79f4b4559de9220cac4c was wrong on two accounts: a bug and wrong solution. It has been reverted.

@bsongis @kilrah Now let's discuss how to solve this problem:

The setting to zero was done because in gtest we do not allow negative value for current sensor. 

Obviously we need an option that prevents some sensor values from becoming negative. Ones such case is the current sensor. Other sensor values might also need this (maybe).

There are several options to solve this:
* we go with the current solution and we add if() case for VSPEED (like my attempt, but with corrected condition) 
* we remove this feature altogether - all values can be negative
* we introduce a new setting for each telemetry value that defines if value can be negative.

**Comment by kilrah** [comment]
I don't see why we disallow negative values, so I'd remove the check altogether...
