### ISSUE TITLE
[Bug][OpenTX 2.0.17][Companion] No RSSI alerts

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#2446]
Hi folks,

When I'm using the F4 button under the simulator (telemetry test), if I'm changing the RSSI nothing is happening. No beep, no alarm, no sound announcement.
I don't know if it is only a simulator bug or if this can also somehow impact the OpenTX firmware itself.

**Comment by projectkk2glider** [comment]
Which version?

**Comment by LapinFou** [comment]
2.0.17
I forgot to mention a very important point in order to reproduce the issue: you must launch the simulator from the model edition window.
If you launch it from the main window, the problem doesn't appear.

**Comment by projectkk2glider** [comment]
Confirmed (even in next), the RSSI value changes, but the warning does not sound.

**Comment by projectkk2glider** [comment]
I've found the problem. We use static variables that work first time the simulator is started, but on consecutive starts the initial value is not set again. The culprit here is `alarmsCheckTime` in `telemetryWakeup()`.

This issue is not affected by the way the simulator is started. It works the first time and fails on the second time.

**Comment by LapinFou** [comment]
That was a fast fix!!!
Thanks.
:)
