### ISSUE TITLE
Move to Qt 5

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#2611]
Qt 4 is now a little bit behind ...

**Comment by griebd** [comment]
on the topic of upgrading development tools...
I'm still using gcc 4.8 with no problems so far!

$ arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.8.4 20140725 (release) [ARM/embedded-4_8-branch revision 213147]

For companion, using cmake -DCMAKE_BUILD_TYPE=Release and gcc 4.8, I have no problems except by some warnings (because -Wstrict-aliasing and -Warray-bounds) at compile time.

$ gcc --version
gcc (GCC) 4.8.2

**Comment by raphaelcoeffic** [comment]
And Qt5 has support for retina displays :-)

**Comment by amontefusco** [comment]
Hi Bertrand,
I have just rebuilt on Ubuntu 14.04 both companion21 and simulator21 using Qt5 and Phonon4-qt5.
If you find it useful, I will create my fork  with all the changes in  qt5 branch.

**Comment by bsongis** [comment]
Why didn't tell it before?
I have it stashed here, with Qt5Multimedia instead of Phonon

**Comment by amontefusco** [comment]
I started to work on it today in the afternoon and finished one hour ago :-)

**Comment by bsongis** [comment]
Ok then we will take the merge of both :)
I removed a lot of includes
I am thinking about switching everything to CMake as well ...

**Comment by amontefusco** [comment]
https://github.com/amontefusco/opentx/

Sorry for the delay but I am currently in val Badia and there was an Internet outage just past night.
In the meantime, I fixed a bug (no pulldown menu).

**Comment by bsongis** [comment]
Done!

**Comment by kilrah** [comment]
Cool!
