### ISSUE TITLE
can not find 2.1.X telemetry-lua documentation

### ISSUE THREAD

**Issue by wolkstein** [opentx/opentx#2716]
hi since a few days i try to understand the new 2.1telemetry. maybe i miss something in general, but i can not find any documentation how the new telemetry works. i try to adapt my MavlinkToFrSky S.Bus converter to communicate with my taranis-plus EU version. for example i try to getValue(214)   "cell-min" from lipo sensor. with 2.0.17 no problem but under 2.1.1, for me, no chance to get this value. is there an documentation which describe how you get all available 2.1-telemetry values inside lua scripts?

for a proper s.port sync i try this repository. https://github.com/bsongis/MavLink_FrSkySPort which also sends  FLVSS sensor values.
/g
wolke

**Comment by projectkk2glider** [comment]
Things have changed. There is no official documentation. The most relevant is the discussion on http://www.rcgroups.com/forums/showthread.php?t=2180477 

The obvious change is that telemetry values are no longer available by their old names, because in 2.1 the name of each telemetry value can be user defined. So you get them by their name.
