### ISSUE TITLE
Companion syncronize SD fails

### ISSUE THREAD

**Issue by lvale** [opentx/opentx#2879]
Latest 2.1.3 of Companion and Taranis X9D - B Radio.

If the SD card on the radio is empty (i.e. formatted but without directories) synchronize SD fails. 

I believe the correct action should copy the local computer structure to the SD card, if it corresponds to a valid SD card structure.

**Comment by projectkk2glider** [comment]
Kind of expected. The path to the SD card in the radio is found by looking for `SOUNDS` dir in the root of a drive. Since your SD card is empty, nothing is found and nothing is done. You should be getting this warning:

![screenshot](https://cloud.githubusercontent.com/assets/5950438/9977102/25cdafb6-5efc-11e5-8e53-d2bece5f5674.png)
