### ISSUE TITLE
Corrupt LCD when splash disabled plus long boot time.

### ISSUE THREAD

**Issue by CommanderBatFink** [opentx/opentx#2949]
Firmware: opentx-9xrpro
Version: 2.1.3
When the "splash" screen is disabled, the LCD displays what appears to be a corrupt spatter of pixels on the LCD.   This is often, but not always, accompanied by a very long boot time before "normal" transmitter function can be assumed.
![20151007_211320](https://cloud.githubusercontent.com/assets/15013270/10336573/3382995c-6d41-11e5-8de2-41c6c375fa65.jpg)

**Comment by projectkk2glider** [comment]
Could be related to #2852

**Comment by bsongis** [comment]
Yes, the lcd is not cleared and it is the same problem.

**Comment by pfeerick** [comment]
I don't think this is a closed issue. #2852 Exaggerated this issue due to long boot times - either due to slow SD cards, or file system corruption of some description... but even it the SD card is removed, you get this screen corruption when the SD card is removed (even on the most recent v2.1.7), just not for as long a period.
