### ISSUE TITLE
OpnTxCompanion draw.channel attributes

### ISSUE THREAD

**Issue by rdeanchurch** [opentx/opentx#2956]
![drawchannel-1](https://cloud.githubusercontent.com/assets/4843199/10408315/0b483db0-6eaf-11e5-9d53-b9e1e343f1f6.PNG)	
        lcd.drawChannel( 55, 34, TxV_id, SMLSIZE+INVERS)
	lcd.drawChannel( 55, 44, A1_id, SMLSIZE+INVERS)
A small inconsistency in DrawChannel.
Attribute does not carry over to units in OpenTxCompanion 2.0.17

or to transmitter on      OpenTx 2.0.17.

**Comment by kilrah** [comment]
Is there a reason for mentioning companion specifically (i.e. it works fine on the radio?)

**Comment by rdeanchurch** [comment]
Mentioned on Companion only because that was the only place I tested so far.
TBDone

**Comment by projectkk2glider** [comment]
The same issue is probably also present in 2.1 and should be fixed there too.

**Comment by projectkk2glider** [comment]
Now that I started to port this to the 2.1 branch I realized I do not like this change!

The fact is that the function `putsTelemetryValue()` is also used from the OpenTX firmware many times and for example when editing Logical switch comparison value the correct behaviour is to have only a number part of the value blinking. 

My change in #2977 changes that and the unit also blinks which could suggest to the user that the unit can be changed.

So my vote is to revert this change and leave it as it is. If somebody wants a special formatting for their Lua script, they can do it from the Lua code. But not all changes from #2977 are bad, the change in case for Voltage unit is ok in my opinion. @bsongis and @kilrah I need your opinion.

**Comment by bsongis** [comment]
Right the unit should not blink!

**Comment by projectkk2glider** [comment]
I will revert the offending commits...

**Comment by projectkk2glider** [comment]
Done. 

@rdeanchurch you might not like the result of this issue, because in the end nothing has been done to address your request. The fact is that the same underlying function that is used for Lua is used elsewhere and changing its behaviour the way you want would negatively affect other parts of the code. So decision has been made not to change it.

My I suggest a workaround for you. If you need or desire different formatting/display of the value, then do the formatting in the Lua code and use the lcd.drawText() function to output custom formatted value. That function should support all attributes.

**Comment by rdeanchurch** [comment]
projectkk2glider 
I don't 'love' the result, but don't hate it.
It just seemed a little inconsistent, but use throughout system makes it easy to understand the results of the report.
No sweat, thanks for the consideration.
]
