### ISSUE TITLE
Warning when 2 modules are running in the same time

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#2973]
Everything in the title: a warning if you activate a module but there is already another one activated. Good or bad idea?

**Comment by hrenz** [comment]
I  have  the internal  XJT and an extern XJT running same time 
do you mean  this  combination?
or 2 different Moduls connnected at external Modul socket

**Comment by bsongis** [comment]
Yes I meant this combination. But external != XJT

**Comment by tbs-trappy** [comment]
the issue is that sometimes beginners do not realize that their internal and external (mostly UHF) modules are running. The most popular frequency for UHF pilots is 2.4GHz video, which is totally destroyed by the close proximity between the internal TX module and the video receiver. The idea is to make sure that the internal module is not left running unintentionally when a external module is turned on.

**Comment by bsongis** [comment]
We could add a warning at the time the user chooses an external module (except XJT).

**Comment by tbs-trappy** [comment]
yes, this would satisfy most issues without taking away any flexibility

**Comment by griebd** [comment]
+1, in my case I use a hacked DSM module (for some cheap helis and planes) and been warned would at least save some tx bat power (not that I have forgot any so far, I think :stuck_out_tongue_winking_eye:), if nothing else.

**Comment by janekx** [comment]
I suggest to do it but have posibility this warning permanently disable on model basis but have it by default ON.

**Comment by kilrah** [comment]
Again it would show up only at the moment you enable one module AND another is already on. You should not see it more than once when you set your model up.

**Comment by janekx** [comment]
Ok one time
