### ISSUE TITLE
Alt in top bar

### ISSUE THREAD

**Issue by PieroCo** [opentx/opentx#3047]
Taranis x9d and opentx 2.1.5

In the Companion Telemetry Top Bar when I select Alt, (vario) as the Altitude source all seems OK on the Taranis initially. Observing the Top Bar on the Taranis it will randomly display ft, (x feet) or a number. The number will be 4294967xx, (xx will vari 20-29) and if the vario tone is on, a unusual tone is produced at the same time the 4294967xx is displayed. Sometimes the number continues to be displayed, (constant with xx variable) but vario tone appears to return to normal.

**Comment by projectkk2glider** [comment]
What are your altitude sensor and receiver?

**Comment by PieroCo** [comment]
Frsky Variometer Sensor-high precision and X6R

**Comment by projectkk2glider** [comment]
Was it working in any previous 2.1.x release?

**Comment by projectkk2glider** [comment]
Might be related to #3043 which also displays unusually large numbers.

**Comment by PieroCo** [comment]
Same problem with d4rii but Ok with x8r

I updated directly from 2.0.17

**Comment by PieroCo** [comment]
The problem is only on top bar

**Comment by projectkk2glider** [comment]
That is strange. If its working on X8R then it should also work on X6R they are almost the same.

**Comment by indavis** [comment]
@PieroCo Are you logging the flights? I have two High Precision Varios, and it seems that one of them might be on an older firmware as it occasionally gives me crazy altitude values that throw everything completely off. This sounds exactly like what is going on. When the spurious altitude value comes out, the vario goes nuts because it sees an altitude change from say 300ft up to 16,000ft, and then as it goes back to normal.

I am attaching one of my log files from a Radian glider. I have removed the gps location for my own privacy, but left in the GPS Alt so that you can see it is staying pretty constant. Take a look at row 922 and row 5109. As you can see, for a few log entries after that it has thrown the vario for a real loop. I didn't look down at the display to see if it was causing an issue, but I am guessing the size of the number would cause a problem like is being described above.

Edit: I don't have permission to attach. So I went ahead and posted it on rcgroups in the following message:

http://www.rcgroups.com/forums/showpost.php?p=33159602&postcount=1705

**Comment by janekx** [comment]
Please try to turn on the filter on the vario senzor

**Comment by indavis** [comment]
@janekx If that was directed at me, I just checked my Radian model, and filter was unchecked. I shall check it and see if that helps. I will also refrain from patching my vario just in case we need to test anything. I have another glider with a newer vario that I don't think I have seen these random high altitude values. Which is what I think the original poster is also seeing.

**Comment by janekx** [comment]
I got too bad datas at ASS sensor here https://github.com/opentx/opentx/issues/3043 so try to filter datas to know more

**Comment by projectkk2glider** [comment]
Related to this issue:

>Trying to change what is displayed on the Top Bar using the radio doesn't seem to work. Select it move up or down to change and the only options is (---). Now the radio displays nothing in that location

**Comment by projectkk2glider** [comment]
@indavis your data suggests that the sensor itself is sending bad values. If you look closely you will see that the vertical speed goes berserk (rapid min max changes) when the reported altitude is way off. But this seems to be a different issue from the original one.

One idea for future, perhaps we should include an option to turn on a glitch filter for each telemetry value.

**Comment by projectkk2glider** [comment]
The log file from above in csv format: http://wikisend.com/download/714218/FigNewtons_Radian-2015-10-27.csv

**Comment by indavis** [comment]
I completely agree that my sensor is sending the spurious values. But I haven't looked down at the screen to see if it is throwing the display off like the issue we are discussing. What I do notice is that it throws the vario off exactly like the submitter is suggesting. 

"*The number will be 4294967xx, (xx will vari 20-29) and if the vario tone is on, a unusual tone is produced at the same time the 4294967xx is displayed. Sometimes the number continues to be displayed, (constant with xx variable) but vario tone appears to return to normal.*" is exactly how the vario responds when I catch these. I wish I could just go out and test this some more, but I have to fix the firewall on this glider. I was merely trying to give some data and still think the submitter should make sure logging is on and see if it's his sensor spitting out some data that is out of bounds.

**Comment by PieroCo** [comment]
my vario not send spurios values

**Comment by projectkk2glider** [comment]
I found one issue if Alt is negative the display on the top bar will be a very large number like above.

**Comment by PieroCo** [comment]
@projectkk2glider I checked again. The problem occurs only when the altitude is negative. With all receivers including X8R
