### ISSUE TITLE
Add commandline options to standalone simulator

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#3160]
* radio type
* eeprom file to use (could also be added to the first dialog box)

**Comment by lshems** [comment]
Oh yeah, command line options I can use in a windows link.

Then I don't have to select the one radio I have every time:)

GoGoGo

P.S. option in companion to launch simulator, since it allows to change settings etc and have them saved to the taranis.bin file. Some things cannot even be changed in any other way.

**Comment by bsongis** [comment]
Yes it's a good idea!

**Comment by projectkk2glider** [comment]
Idea is not mine :grin: , but I do like it.

**Comment by pointu** [comment]
The questioning is on on the French taranis forum, something like :
"simulator.exe -f=myTaranis.eepe -m=Salto sc=telemetry"

**Comment by bsongis** [comment]
I hope @projectkk2glider won't choose this syntax!

**Comment by pointu** [comment]
let me know ?

**Comment by kilrah** [comment]
Radio type and eeprom file are easy to do, but anything more needs an interface to the firmware that doesn't exist yet, much bigger job.
