### ISSUE TITLE
Add the support for jpg and/or png

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#3167]
Parent issue #3159

**Comment by projectkk2glider** [comment]
Classic PNG implementation:
* reference implementation in libpng http://www.libpng.org/pub/png/libpng.html
* also requires zlib http://www.zlib.net/

All in one alternative:
* lodepng https://github.com/lvandeve/lodepng

----
Jpeg:
* STM32CubeF4 from ST has Jpeg library http://www.st.com/web/en/catalog/tools/PF259243

**Comment by projectkk2glider** [comment]
A couple of questions for @bsongis:
* do we need read only capability or write (create) also?
* what kind of format should be returned from the read function - ie RGB, how many bits per color, etc..
* maximum image dimensions

**Comment by bsongis** [comment]
I suggest we add a byte to remind the format of the loaded bitmap. It will save CPU

**Comment by bsongis** [comment]
- Write support would be a bonus and only on PNG, if implemented, I think it would be good to have snapshots in PNG format rather than BMP
- Ideally the format returned would be the one which would be the quickest to display, (without loosing quality of course).  I suggest we add a byte to remind the format of the loaded bitmap, just near the width and height. It will save CPU
- Maximum image dimensions. Given we have plenty of RAM, it would be the LCD size, no? The malloc should use the external RAM of course.

**Comment by projectkk2glider** [comment]
I will look into PNG tonight....

**Comment by projectkk2glider** [comment]
My current favourite is https://github.com/nothings/stb/blob/master/stb_image.h which supports loading a bunch of formats, we can chose which ones we want, others are not compiled in.

**Comment by bsongis** [comment]
Seems good!

**Comment by projectkk2glider** [comment]
More resources:
* https://news.ycombinator.com/item?id=8600634
* jpeg compressor https://github.com/richgel999/jpeg-compressor

**Comment by projectkk2glider** [comment]
This can be closed now, done.

**Comment by RCdiy** [comment]
So now we can use a rgb PNG file with transparency without needing to index it to 16 colours?

**Comment by kilrah** [comment]
Yes
