### ISSUE TITLE
Timer3 

### ISSUE THREAD

**Issue by PieroCo** [opentx/opentx#3206]
Timer3 (persistent) in statistic is correct but in telemetry page is wrong.

![screenshot-1](https://cloud.githubusercontent.com/assets/7857600/12144731/075447b4-b48a-11e5-9e8f-31ab069ea7fa.jpg)

Opentx 2.1.6 and 2.1.7

**Comment by projectkk2glider** [comment]
The "bug" is in the TM3 name which is actually a global timer. this one was in OpenTX for a long time and was named TM3 since we had only two model timers. Now that timer 3 was added, the name TM3 should be changed.

So Timer3 and TM3 are different timers! To reset TM3 hold ENT in STATS screen (I think)

**Comment by bsongis** [comment]
I see 2 bugs:
- [ ] In statistics a timer > 60 minutes should be displayed hh:mm:ss, otherwise mm:ss
- [ ] The same in telemetry screen

**Comment by bsongis** [comment]
@projectkk2glider would you check my fix in 'next'? I will backport it to 'master' if you like it

**Comment by projectkk2glider** [comment]
Looks perfect :+1: 
![snapshot_01](https://cloud.githubusercontent.com/assets/5950438/12177069/b36dff32-b56a-11e5-920d-610c495c2661.png)
![snapshot_02](https://cloud.githubusercontent.com/assets/5950438/12177071/b5031472-b56a-11e5-8b86-a46586991a3e.png)
