### ISSUE TITLE
Offsets don't show on Inputs headlines

### ISSUE THREAD

**Issue by tomkfly** [opentx/opentx#3400]
When an Offset is used in mixes it shows in the mix line, but not in Inputs. This caught me out today as when I flicked the rate switch Maidening a new model model which was very sensitive on Aileron I flicked the rate switch and it started to roll. Fortunately It was 3 mistakes high. An offset had crept into my Aileron Input mid rate (I must have somehow entered it accidently when setting up the Inputs) and on checking through all my settings I missed it, as I didn't realise offsets didn't show. Not a priority, but I think it would be a useful enhancement if offsets could be listed on the Input line.

**Comment by projectkk2glider** [comment]
If you mean in Companion, then already fixed #3357. Is it on the radio?

**Comment by tomkfly** [comment]
Radio and Companion 2.1.7

**Comment by projectkk2glider** [comment]
Just checked. The `offset` on the radio is not shown in both Inputs and Mixes. I am sure this is because of the space limitations. @bsongis @kilrah @mhotar can we do something to squeeze the offset there?

Current display:

![snapshot_04](https://cloud.githubusercontent.com/assets/5950438/14235003/d985292c-f9f1-11e5-9c7c-4d196a24209c.png)
![snapshot_05](https://cloud.githubusercontent.com/assets/5950438/14235004/dbe1afce-f9f1-11e5-98dd-b8ddb611299e.png)

**Comment by kilrah** [comment]
Offsets have never been shown on either screen, indeed because the available space is used for other things.
