### ISSUE TITLE
Changing MAX to USE

### ISSUE THREAD

**Issue by Oldgibber** [opentx/opentx#3447]
Brought a concern up about MAX up some time ago, but it seems to have been lost with the plethora of other work, and so have closed it down. However, this suggestion seems a very simple fix which makes things more logical.

There was general agreement that MAX was not ideal, but then having MAX/MIN or FIX or SET were not ideal either. How about USE?

USE Weight(+100%) Switch(SA↑)
USE Weight (0) Switch(SA-)
USE Weight(-100%) Switch(SA↓)

It would appear to be a very simple programming change, and if, as I suppose, MAX is simply a stored code number in the eepe file then on future versions it would still be correct but with USE instead of MAX

**Comment by hrenz** [comment]
Were is your Problem, cant see any
Max is Max 
and Max is +100%
you can tell it mickymouse but its +100%

**Comment by Oldgibber** [comment]
Its simply not intuative. Its clumsy. 

How does a new user know MAX means +100?

**Comment by tomkfly** [comment]
I don't see how USE is any more intuitive.

**Comment by kilrah** [comment]
> How does a new user know MAX means +100?

The same way they's know USE is +100% since it's no more intuitive - either by reading docs or trying it.

And given changing it would render years of documentation efforts obsolete it makes absolutely no sense to change it "just to change it", which is why the old issue would have been closed... and this one is too.
