### ISSUE TITLE
Emergency shutdown

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#3600]
For radios with power button and power switch:
* in mixers thread, monitor power switch/button, if pressed continuously (or turned off) for X (10) seconds, and main thread is dead, power off.

One example where this would come in handy is #3599, now the only way to turn off the radio is to remove the battery.

**Comment by kilrah** [comment]
+1, insisting on the "and main thread is dead". We could also do another improvement at the same time, someone raised a valid point that should the switch somehow stick pressed it should of course not shut down... We could do the same as on power on with the X9E where if the button is pressed for more than X we turn off again, and there cancel the shutdown if the button stays pressed for more than a couple of seconds after the shutdown "delay".

My X9E has the power switch that tends to stick, and often it will stay on the "ZZZ" screen after shutdown, but that goes unnoticed since backlight is off.
