### ISSUE TITLE
Switch X9E 

### ISSUE THREAD

**Issue by hobby1946** [opentx/opentx#4343]
Switch > SH (2-Position and Toggle) do not move back to -100% (0%)

**Comment by hobby1946** [comment]
in Companion N362 Simulator !

**Comment by projectkk2glider** [comment]
I actually can't reproduce this with N362! Using Mixer with source SH on CH1:
![screenshot](https://cloud.githubusercontent.com/assets/5950438/22440062/562640dc-e732-11e6-868e-d24b3d72444e.png)
![screenshot](https://cloud.githubusercontent.com/assets/5950438/22440065/57c8ce00-e732-11e6-9a14-8f3ee228c6d1.png)

**Comment by hobby1946** [comment]
Switch SH is OK !

Switches  SI -> SP is not ok !
Start ->           -100%
Switch on ->     100%
Switch Off -       0%

**Comment by mpaperno** [comment]
It finally dawned on me why my fix actually did anything... 😄    The firmware expects a "3-position signal" for switch slots that can take them.  So that's why the 2-pos. switches worked correctly in simulator when in standard 2-pos slots (except Horus SH), and not when installed in a 3-pos slot (same with `simu`). 

Check the outputs at channels 5 - 8  (upcoming next-gen UI with separate outputs panel... WIP  😉  )

![image](https://cloud.githubusercontent.com/assets/1366615/22448891/5c42c2ae-e72a-11e6-8db9-f12abe1d9ed8.png)
