### ISSUE TITLE
request: make backups of X7 and X9 exchangeable

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#4510]
currently, x9 backups are not recognised by X7 restore. In the field model exchange becomes almost impossible.

**Comment by schwabe** [comment]
That would require an epprom change, so not going to happen in 2.2

**Comment by 3djc** [comment]
Exchange between different capabilities radios have to go through companion

**Comment by kilrah** [comment]
Data is incompatible due to different hardware meaning different "meanings" of the same values. 

Conversion is necessary, which is provided in companion but won't be implemented on the radio for code size and maintenance reasons.

We are discussing unifying the data format for all ARM radios which may take care of it.
