### ISSUE TITLE
Taranis Q X7  Telemetry gps display issue

### ISSUE THREAD

**Issue by wolflonezx11** [opentx/opentx#4533]
hi all 
OpenTX 2.2 RC10

1. Taranis Q X7  Telemetry GPS display issue

00.23
21.45  

Display issue

2. Taranis Q X7  Telemetry  VOTG MENU Display 불량 
menu Select none

**Comment by 3djc** [comment]
1. fixed already, will be available in next RC

2: no idea what you are talking about

**Comment by Jmelz** [comment]
On Q X7, telemetry pages only show GPS with 2 decimal places which leads to a very big area of uncertainty (inaccurate):

![gps](https://user-images.githubusercontent.com/29664080/27494634-c63fd62a-581c-11e7-8d0e-5e1be45f979c.PNG)

**Comment by 3djc** [comment]
With some coordinates, all the available space is fully utilized. If you want to allocate more space to it, you can create an Lua display for it

**Comment by Jmelz** [comment]
Sounds great, but I'm a noob :)

It seemed like there was enough room for 2 more digits, which is why I came here to ask. Seems like it could be made configurable; such as precision in other sensors.

Also my attempts at making GPS stay on the screen after losing telemetry (no rf signal) are poor when I try via LUA.

**Comment by 3djc** [comment]
Whats your GPS type ? On mine with display set to DMS : 

![image](https://user-images.githubusercontent.com/5167938/27495264-8ed22f96-5851-11e7-8855-67774e521918.png)

Your seem set on NMEA in radio settings

**Comment by Jmelz** [comment]
I am speaking of NMEA, not Decimal Minutes Seconds. I can see your point about degrees minutes seconds filling the screen, but NMEA does not.

The source is a bit complicated, but I know it feeds okay into Tower on Android. Eagletree Vector --> Dragonlink v3 receiver --> Dragonlink v3 transmitter --> PPM input on back of Q X7.

**Comment by 3djc** [comment]
You need to account for 1 more digit upfront since it can have 3 digits, I think it won't leave two more spaces

**Comment by Jmelz** [comment]
Not sure I follow you :(

If you change to NMEA in main settings, you'll see. There is space for more digits, it's just a design decision.

To use your example, would not the Decimal Minutes Seconds (or Degrees Minutes Seconds is better to say) also use up more space? 

Say it was (fake) 170*13'11.34"N - that would extend past the center...

**Comment by 3djc** [comment]
It also matches x9 display in NMEA:

![image](https://user-images.githubusercontent.com/5167938/27495540-96552128-5852-11e7-82c9-2211986ee773.png)

**Comment by 3djc** [comment]
What I mean is your lat starts with 2 digits, it seems like a lot of room left, but not for this guy in Asia for exemple:

![image](https://user-images.githubusercontent.com/5167938/27495642-0bb2252e-5853-11e7-8189-04b6fcc761fa.png)

**Comment by Jmelz** [comment]
Okay, understood - but when the person in Asia uses the other format, does it not also push over?

![gps](https://user-images.githubusercontent.com/29664080/27495754-32a9eafe-5821-11e7-8fd2-8b1cb3d946ae.PNG)

I use several devices with different capabilities and have to try to standardize on a format they can all display, so it ends up being lowest common denominator type deal...

Tbeacon is great, they say this in their manual:

Different GPS formats and their corresponding location error tolerance: 
DD ММ SS.S    3 meters 
DD ММ.МММ   2 meters 
DD.DDDDD      1 meter 
DD.DDDD        10 meters 
.DDDDD           1 meter 
.DDDD            10 meters 

Here, you see that currently, opentx displays a "level 4" accuracy: https://en.wikipedia.org/wiki/Decimal_degrees

I'm proposing level 6.

So as a result of that, I ended up using DD MM.MMM with my eagletree vector, as it can only display 3 formats, and the eagle eyes telemetry box can only do 1 format. So, DD MM.MMM is shared by everything in my hanger now, even though it is not the most precise.

Ideally, that is what I would use here, but I at least need to use something that is more accurate than the current NMEA format (which is the right format for me) implemented in opentx - which is several meters instead of 2. So even just 1 more decimal place would help a bunch, but 2 more would be perfect! :)

The reason for my request is to aid in finding a downed FPV model, in case video is lost but rf link continues.

**Comment by 3djc** [comment]
Then just launch this LUA when in that situation (by the way, in 2.2, you'll get last transmited coord even if your RF link if down ;))

[GPS_Coord.zip](https://github.com/opentx/opentx/files/1099475/GPS_Coord.zip)

![image](https://user-images.githubusercontent.com/5167938/27506599-bace1f28-58bb-11e7-9b73-57f266e77a4c.png)

**Comment by Jmelz** [comment]
Thanks very much! I was told that the last coordinates would be logged, but so far I'd not had any luck seeing the coordinates on the screen in any scripts after powering down the plane (killing the link). I'm running 2.2 already.
EDIT: hrm--- I tried this script and as soon as I pull the power on the plane killing the rf link, I hear "telemetry lost" (normal) but then the screen says not currently avai (trails off the screen) and the coordinates have disappeared.

It's quite interesting because when I go to the sensors page, I can still see the last transmitted values as you said - it's just that the scripts seem to ignore them...

**Comment by 3djc** [comment]
You can have an updated version of the script running in the background too, to record the value while available. Have a look in the opentx Lua doc toward the end at gps data handling

**Comment by Jmelz** [comment]
Yes, I noticed that. I also saw the previous author used it in the script I am modifying:

return{init=init,run=run,background=background}

but even in his script, it seems to blank the coordinates when telemetry is lost... Must be something I'm doing wrong or not understanding. Both the builtin telemetry screens (any of the 4 custom setup pages) or the lua scripts all seem to lose GPS coordinates, while the sensor values are still holding their last known value.
