### ISSUE TITLE
Dropping mixer lines shifting one line

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#4622]
when dragging and dropping a mixer line, sometimes it gets dropped on the previous mixer line instead of the mixer the black line is put after.

**Comment by elecpower** [comment]
Noticed this behaviour some time ago when fixing the drag and drop before line 1 issue. My testing showed that when moving the mouse very slowly across mixer lines there is a very small shift in the black line. That small shift is enough to affect which line the dragged line is dropped onto.
Since it was a minor annoyance and once I had worked out where to drop didn't bother to pursue.
Not sure if it is an inherent QT issue, related to the padding (if still exists) between mixer lines or even OS dependent.

**Comment by projectkk2glider** [comment]
Which version? Is behavior in 2.1 and 2.2 different - they use different QT verisons?
