### ISSUE TITLE
TaranisQ X7 - No Wizards starts for new plane N364

### ISSUE THREAD

**Issue by dklueh79** [opentx/opentx#4628]
Setting up a new plane, the wizard for a new model doensn't open. The lua wizards doesn't work on manual execute.

**Comment by 3djc** [comment]
There is currently no wizard for x7

**Comment by dklueh79** [comment]
Ok, then the sd-card content shouldn't contain the wizards at all

**Comment by 3djc** [comment]
Unless I'm mistaken, it doesn't

**Comment by kilrah** [comment]
It doesn't, you probably took the x9 zip or copied your card from an x9 that had it.

**Comment by henriquedesousa** [comment]
Is it technically possible for someone to port it to the QX7, taking into account the reduced screen?

**Comment by kilrah** [comment]
Anything can always be done, it's only the amount of effort that varies.
In this case since the wizard was made to use all the nice graphics capabilities of the X9 screen (that the X7 doesn't have) all the UI basically needs to be redone differently. 
Nobody has shown interest in doing that job so far.

**Comment by henriquedesousa** [comment]
I just found that OpenTX companion has the same wizard, so we're good for now. Many thanks.
