### ISSUE TITLE
Companion 2.2.0N365 Simulator inconsistent trims range/adjustment using buttons and sliders

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#4671]
All trims -25 to +25 via dragging sliders but in most cases -24 to +24 via up/down arrow buttons. Sometimes -25 or +25 if drag slider away from max +/- and use buttons to return to last max +/-.

Tested for Taranis X9D+ on Ubuntu 16.04

**Comment by kilrah** [comment]
Where are you looking at the value? Some places may display 24 due to rounding.

**Comment by elecpower** [comment]
![screenshot from 2017-03-22 22-32-40](https://cloud.githubusercontent.com/assets/15316949/24195904/b03937ce-0f4f-11e7-8408-cbdfdbe45f71.png)
Radio sticks window range +/- 25% via sliders or generally +/- 24% via buttons.
Also checked Radio outputs and channel range is always -/+24%

**Comment by mpaperno** [comment]
What does it show for outputs on the simulated radio itself?  That's what we really need to match.  

I think the Radio Outputs rounding issue is fixed by a recent commit.

Those trim sliders are a bit of an anomaly since they don't exist on the actual radio (really just there for convenience).  There is another issue open about them as well (not being constrained when trims are disabled).  Not saying that as an excuse, but it's really the trim buttons which simulate the radio hardware properly.

**Comment by elecpower** [comment]
As you say rounding but trim 24% vs 25% does affect the simulated radio value.
![screenshot from 2017-03-23 06-52-07](https://cloud.githubusercontent.com/assets/15316949/24217900/77444936-0f95-11e7-9f46-234b3854f466.png)
![screenshot from 2017-03-23 06-52-28](https://cloud.githubusercontent.com/assets/15316949/24217901/7746dd40-0f95-11e7-8a62-165ede8bf4ac.png)

**Comment by kilrah** [comment]
24.2 is actually correct and consistent with the radio.

**Comment by mpaperno** [comment]
With current `next` code the only rounding issue I see is in the X/Y indicators next to the sticks themselves.  The Radio Outputs display rounds correctly (also for negative values), and the trim sliders set the same values as using the buttons.  However the X/Y values are not rounded the same way as the outputs right now (same issue as we had there).  Also discovered another issue -- those X/Y numbers don't update on trim change until the virtual stick is moved.

However...  I think the bug is that those X/Y values include the trim adjustments at all.  Shouldn't they just show the virtual stick position?  The final channel output is up to the radio, after all, and that's what the radio output screens are for.  Those X/Y values do not take any other radio outputs into account so I'm not sure why trims should be included.

Now maybe it would be useful to show the trim outputs somewhere in the simulator UI... which could be arranged (say, in the Radio Outputs widget, or next to the trim controls).  But I think those X/Y value by the sticks should show where the virtual joystick is actually positioned.

Opinions?

**Comment by 3djc** [comment]
I think those value should be stick only too. If you look at input screen on the radio, it does not take trims into account either.

**Comment by kilrah** [comment]
Indeed, especially given that the trim isn't even necessarily enabled, but this % currently includes it even if not.
Kinda makes no sense anymore with the inputs and their flexibility.
