### ISSUE TITLE
QUESTION: How to use as bridge

### ISSUE THREAD

**Issue by ekifox** [opentx/opentx#4697]
Hello, in advance I apologize, that I ask a question in the error list, but nevertheless.
1) Is it possible to send TX commands (emulate joysticks) from the computer to the drone through Taranis?
If not at the moment, is it possible to add it in new versions?
2) Is it possible to use USB as a serial bus? May be get telemetry data from bus over USB?
3) Can the administration create a chat on the Gitter for direct communication?

**Comment by schwabe** [comment]
1. If you setup your computer as trainer input, e.g. by using the sbus input, yes.
2. Yes. But currently it serves only as a CLI iirc. Other modes could be implemented.
3. We use rocket.chat chat instead of gitter. Just join the #general channel.

Btw.: This is a bug report and not a forum for asking for that use forums or our chat.
