### ISSUE TITLE
EEPROM Flashing problems

### ISSUE THREAD

**Issue by Phil1988** [opentx/opentx#4704]
I have problems Flashing my Turnigy 9X using an arduino Nano with a 100Ohm resistor between RST and 5V.
I can flash the OpenTX firmware but I always getting "EEPROM Warning" errors on flashing.
The EEPROM is then replaced by the "original" one during the firmware flash.

Here is the log from the flashin process:

C:/Program Files (x86)/OpenTX/Companion 2.2/avrdude.exe -c avrisp -p m64 -b 19200 -P com5 -U eeprom:r:/backup-2017-03-27-132418.bin:r
-------------------

avrdude.exe: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.02s

avrdude.exe: Device signature = 0x1e9602
avrdude.exe: reading eeprom memory:

Reading | ################################################## | 100% 3.51s

avrdude.exe: writing output file "/backup-2017-03-27-132418.bin"

avrdude.exe done.  Thank you.

-------------------
C:/Program Files (x86)/OpenTX/Companion 2.2/avrdude.exe -c avrisp -p m64 -b 19200 -P com5 -U flash:w:C:/Users/User/AppData/Local/Temp/8096-flash.hex:i
-------------------

avrdude.exe: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.02s

avrdude.exe: Device signature = 0x1e9602
avrdude.exe: NOTE: FLASH memory has been specified, an erase cycle will be performed
             To disable this feature, specify the -D option.
avrdude.exe: erasing chip
avrdude.exe: reading input file "C:/Users/User/AppData/Local/Temp/8096-flash.hex"
avrdude.exe: writing flash (50518 bytes):

Writing | ################################################## | 100% 47.29s

avrdude.exe: 50518 bytes of flash written
avrdude.exe: verifying flash memory against C:/Users/User/AppData/Local/Temp/8096-flash.hex:
avrdude.exe: load data flash data from input file C:/Users/User/AppData/Local/Temp/8096-flash.hex:
avrdude.exe: input file C:/Users/User/AppData/Local/Temp/8096-flash.hex contains 50518 bytes
avrdude.exe: reading on-chip flash data:

Reading | ################################################## | 100% 28.17s

avrdude.exe: verifying ...
avrdude.exe: 50518 bytes of flash verified

avrdude.exe done.  Thank you.

-------------------
C:/Program Files (x86)/OpenTX/Companion 2.2/avrdude.exe -c avrisp -p m64 -b 19200 -P com5 -U eeprom:w:/backup-2017-03-27-132418.bin:r
-------------------

avrdude.exe: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.02s

avrdude.exe: Device signature = 0x1e9602
avrdude.exe: reading input file "/backup-2017-03-27-132418.bin"
avrdude.exe: writing eeprom (2048 bytes):

Writing | ################################################## | 100% 96.07s

avrdude.exe: 2048 bytes of eeprom written
avrdude.exe: verifying eeprom memory against /backup-2017-03-27-132418.bin:
avrdude.exe: load data eeprom data from input file /backup-2017-03-27-132418.bin:
avrdude.exe: input file /backup-2017-03-27-132418.bin contains 2048 bytes
avrdude.exe: reading on-chip eeprom data:

Reading | ################################################## | 100% 3.51s

avrdude.exe: verifying ...
avrdude.exe: 2048 bytes of eeprom verified

avrdude.exe done.  Thank you.

-------------------

I can read/backup the EEPROM image but as I want to write it, Companion 2.2 (companion-windows-2.2.0N366) I get "Can't extract RADIO/radio.bin".

If I try it with Companion 2.1.9 I get an "Invalid Models and Settings file C:/.... " error.

How can I solve this problem?
Would be a real big problem if I have to set everything up from the scratch eacht time I flash a new firmware...

**Comment by lezabour** [comment]
same problem here ;( did you find a solution?

**Comment by Phil1988** [comment]
Sadly no... and I am still waiting for my USBasp flasher to arrive to check if it solves this problem.
But nice to hear I am not the only one with this problem.

Please keep me updated if you find a solution - so will I do!

**Comment by Wesie** [comment]
For the 2nd Issue I'll believe, that is normal, because an Eeprom with the Modells are not downward compatible. This means, you can go only up, but never down (In this case its nicw to have a backup feom your models) 
The first one I couldn't see the one with N370. 
I've make a backup and restore them (9X Atmega 64A)
Maybe it's solved in the meantime?

**Comment by Phil1988** [comment]
What do you mean with "downward compatible" ?
It is not possible to download any model settins - even after I install the latest firmware on the TX, setup a new model there and try to download this model/eeprom.

So I can always just "overwrite" the existing firmware and not do any backup!

I also have a 9X with an ATMEGA 64A.

**Comment by kilrah** [comment]
Companion is most likely broken and doesn't take into account the fact that the 9x eeprom format hasn't been updated in a while, neither have the features. 
None of us has been using a 9x for years. We don't have any test hardware anymore so support for it is currently "best effort" with rather low investment. 

You could jsut stay on 2.1, since there is nothing new at all in 2.2 for the 9x. Not even sure 2.1 had anything over 2.0.

**Comment by Phil1988** [comment]
2.1.9 didnt worked as well... so what is the latest working version for the 9x?

Its really a pitty that this transmitter is not fully supported (anymore) because the transmitter itself and this software are great...

**Comment by szalat** [comment]
Hello, I want to add my two cents here. Since I've read (very sparse info) about bug in new version affecting 9X (https://www.open-tx.org/2018/02/26/avr-pull) I was searching for more about it, found only this bug report.
I think it will be great to add some information to main site, e.g. just like kilrah wrote:

> (...)
> None of us has been using a 9x for years. We don't have any test hardware anymore so support for it is currently "best effort" with rather low investment.
> 
> You could jsut stay on 2.1, since there is nothing new at all in 2.2 for the 9x. Not even sure 2.1 had anything over 2.0.

I think it is vital information for 9X users searching for new firmware (following Companion reports: hi there, we have new version): 
"don't use new version of Companion nor Opentx. Just stick with version xxx."

Regards !

**Comment by 3djc** [comment]
I have reworded that post.

**Comment by szalat** [comment]
Thanks 3djc! This makes more clear situation for 9x users.
