### ISSUE TITLE
Turnigy 9XR pro open TX 2.2 N371 

### ISSUE THREAD

**Issue by old4570** [opentx/opentx#4938]
1) Installing firmware AETR , I get  RETA @ the transmitter (?) 
2) openTX crashed deleting all settings ( eeprom error ) 
3) openTX locked up on start , removing SD card seemed to solve the issue 
( About 4 hours of use ) 

I deleted all files and software ( companion ) from my puter ..
Downloaded everything fresh , and re - installed .. 
Seems to be running ok , ( 10 minutes of use )

**Comment by kilrah** [comment]
1. There is no such thing as "AETR Firmware" you set that in the general settings so that _subsequent_ new models use that setting
2. Unless you known and explain everything you did with the settings there isn't much we can do, it's common to get there by usage error
3. Try formatting and reloading card contents.

Does not look like any of them are OpenTX problems, please complete if you have more details backing it and we'll reopen.
