### ISSUE TITLE
Unexpected behaviour when Diff and Trim are specified in the same mix.

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#503]
Firmware r2768 - board: taranis

Specifying Diff and Trim in the same mixer line leads to unexpected behaviour
- Diff is currently applied to the Trim value. This leads to lower trim sensitivity on one side than the other. It will also produce unwanted camber changes when applying trim on a dual-aileron setup.
- Servo movement is incorrect on one side if trim applied
- Crossover point for diff is incorrect

Seems that OpenTx does not take into account trim offset when processing diff. I'm working around this by splitting the Diff and Trim into separate mixes, but it's a bit untidy and requires extra mixer lines.

PS thanks for all the good work :-)

**Comment by JivaroFAD** [comment]
I think you should re-opent this issue.

Please read the following test (works with curve or diff, that's the same) with 2.0.99 :
Stick Aileron, ratio = 25%
CH1 : source = aileron, mixratio = 100%, diff = 50%
CH2 : source = aileron, mixratio = -100%, diff = 50%

Put aileron stick on max right/left : CH1 = +25/-12.5, CH2 = -12.5/+25
=> OK, differential works normaly with stick alone
Now put aileron trim on max right : CH1 = +25, CH2 = -12.5
=> OK, differential works normaly with trim alone
Put again aileron stick on max right/left : CH1 = +50/0, CH2 = -25/0
=> KO, differential works abnormaly with trim + stick
      we should expect : CH1 = +50/+12.5, CH2 = -25/+12.5

Now, put trim at 0 and add +25 mixoffset to each : CH1 = +25, CH2 = +25
=> OK, offset works normaly
Put again aileron stick on max right/left : CH1 = +50/0, CH2 = 0/+50
=> KO, differential works abnormaly with stick + mixoffset
      we should expect : CH1 = +50/+12.5, CH2 = +12.5/+50

In my mind, normal operation should be :
Ouput = (MixOffset + Trim * +/-Diff + Stick * StickRatio * +/-Diff) * MixRatio

Or, a little better, assuming that trim effect can be reduce proportionnaly to stick ratio :
Ouput = (MixOffset + (Trim * +/-Diff + Stick * +/-Diff) * StickRatio) * MixRatio

Note : would I prefer applying MixOffset to input (instead of ouput as actualy) because it makes more sense for uncentered mixes (like gaz or airbrakes to elevator compensation). Moreover, if ouput needs to be offseted, it can easily be done with an additionnal line mix.
