### ISSUE TITLE
Reassign sensors to inputs, mixes, special functions

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#5083]
The current way sensors are used is confusing and cumbersome. If I bring to another receiver and back, I have to rediscover the sensors. Fine with that. 

But even when they are automagically named the same as before, there is no guarantee that previous assigned sensors still work on inputs, mixes and others stuff.

So you do not only have to rediscover every time, but also very carefully check all uses of sensors.

Thus had me nearly crash a plane, since I only use rssi, rcbatt and alt, and they are nicely rediscovered with the same name, suggesting they work as before.

**Comment by kilrah** [comment]
Of course not, the name isn't meaningful at all, it's just for display. Index in the table is what counts.

But you do not need to rediscover when changing receiver with the same sensor config.

**Comment by lshems** [comment]
D and X do have a different setup. So really confusing.

Also, after rediscovery, assignments do get lost.

But ok. I will live with it. Though it still seems dangerous to me to give
the impression things have been recognised by giving names. It surely
doesn't invite to check sensor settings after discovery, if you have been
restoring or copying models.



Op 7 jul. 2017 21:07 schreef "Andre Bernet" <notifications@github.com>:

**Comment by projectkk2glider** [comment]
> Though it still seems dangerous to me to give
the impression things have been recognized by giving names. It surely
doesn't invite to check sensor settings after discovery, if you have been
restoring or copying models.

I slightly agree with this. Do you have any good suggestion how this should be conveyed to the unsuspecting user?

**Comment by schwabe** [comment]
Maybe when deleting a sensor/all sensors, check if a sensor is used somewhere and then warn them that a new sensor with the position will take over on rediscover?

**Comment by geofrancis** [comment]
Why not keep the assignments in logical switches/special functions even after sensors are deleted

**Comment by kilrah** [comment]
As mentioned earlier the references are broken since discovery order is random, no way for us to know what you intend to be what. The references ARE kept, which is the whole issue since after a rediscovery they will likely not refer to the correct sensor anymore.

**Comment by geofrancis** [comment]
yes i mean just keep the name in the logical switches but highlight that the sensor is no longer what it expects with a star or in brackets or something like that. so you know what the sensor should be rather than what random sensor it has assigned.

when you have 20+ logical switches it becomes a bit of a nightmare.

**Comment by kilrah** [comment]
Because the switches don't know the name. They only know they refer to "sensor 1", then for displaying sensor 1's name is called up. When the sensor is deleted the name is deleted too.

**Comment by geofrancis** [comment]
Is there no unique value that can be read from the sensors like smartport id or is that handled by the xjt module and too low level for opentx to access?

**Comment by geofrancis** [comment]
is there no unique value that can be read from the sensors like smartport id or is that handled by the xjt module?

**Comment by kilrah** [comment]
Of course and it is. And it is stored in the sensor data. And it is lost when the sensor is deleted.
The system is too flexible to be able to take guesses. Some people have 4 current sensors, which one are you using where?

It's dead simple really - don't delete sensors unless you have a really good reason.

**Comment by geofrancis** [comment]
if opentx sorts the sensors on discovery using that unique value rather than the random order of discovery then if you deleted all your sensors then rediscovered them again it would always go into the same order as long as the number of sensors has not changed.

**Comment by kilrah** [comment]
That would break every setup where you relaunch discovery later to say just add one new sensor. And again can't work on setups with multiple of the same sensor.

**Comment by geofrancis** [comment]
you could still add single sensors but yes you couldnt refresh all of them without changing the order and then it would only effect the order of the sensors that come after the sensor you added rather than them all random.

It would still work for multiples of the same sensor, it would still get every other sensor correct and you would just be left to sort those 2 or 3 sensors that have matching ids rather than everything random.

currently every setup is currently broken anytime a refresh is done, this would sort out almost all of that apart from that single case if refreshing after added a sensor 

even things like copying a model is made difficult, even if its an identical machine with identical receiver and flight controller putting out identical sensors it still ends up totally random if you do discovery so most of your time is spent fixing logical switches and inputs that use telemetry.

**Comment by kilrah** [comment]
> currently every setup is currently broken anytime a refresh is done

But the point is you should almost never need to do a "refresh"! 

> even things like copying a model is made difficult, even if its an identical machine with identical receiver and flight controller putting out identical sensors it still ends up totally random 

Nope it should match perfectly.

That's the whole point, you're trying to find unsuitable solutions to a problem that doesn't exist in the first place if the system is used correctly.

**Comment by geofrancis** [comment]
how can random be a good way of doing anything? all im saying is make some order to the sensors, doesnt matter if its frsky id or even alphabetically. just so long as they get ordered the same each time.

**Comment by schwabe** [comment]
The order is not random, it only seems random, it is actually the order in which the sensors are discovered. As @kilrah explained your flaw is to delete all sensors. 

We might need to point out the relation of sensor to position more clearly.

And even your approach has flaws. GPS sensor for example only start sending (all) telemetry after getting a fix. 

We could also only mark a sensor as deleted and reuse them if it is rediscovered but I would oppose that solution because would expect then some magic ordering and it only fixes your special case.

I think the case that someone switches between D and X receivers on the same model regulary is not worth supporting by us. Even if you do, just copy the model.

**Comment by geofrancis** [comment]
yes i know its ordered in order of discovery but that is totally random. all im saying is if you used something other than the order of discovery it would keep the sensors in the same order.

this would apply to the logical switches too since when trying to select an telemetry input they are also listed in the order of discovery so its always in a different order model to model so it gets rather annoying scrolling through sensors.

**Comment by flarssen** [comment]
#3354 would make it easier to have your own standard, but will of course lead to problems if users, unaware of the connection, rearrange the order after references are made.
What if all references are based on a combination of physical-, data- and group ID? Then the list order can be anything, perhaps also based on these ID's in that order, and alerts can be given if a referenced sensor is missing.

**Comment by geofrancis** [comment]
opentx 2.0 was actually easier to set up with sensors, since they didnt need discovered they would always be in the same order.

i dont care what the order is as long as its repeatable.

**Comment by kilrah** [comment]
> What if all references are based on a combination of physical-, data- and group ID?

Again that would break whenever you discover extra sensors after initial discovery.

**Comment by geofrancis** [comment]
adding another sensor would only shift the sensors that come after the new sensor by 1 position . when a new sensor is discovered and added to the list it could check if there are references to any moved sensor and change them accordingly.

A simpler solution would be if it just ordered them for initial discovery, then add sesors just put them on the end of the list like it does currently. it would mean the sensors would be always in the same order apart from any single sensor that was not part of the setup initially.

It would mean adding sensors in logical switches etc would be much easier since they would be in the same order accross different setups.

**Comment by flarssen** [comment]
"Again that would break whenever you discover extra sensors after initial discovery."

If my voltage sensor is referenced (in display, LS etc.) as 030210 instead of index 4, I can't see how an extra sensor could break this. 
Not sure how it would work out performance wise. Then there is calculated sensors which doesn't have these ID's.

**Comment by kilrah** [comment]
> A simpler solution would be if it just ordered them for initial discovery, then add sesors just put them on the end of the list like it does currently. it would mean the sensors would be always in the same order apart from any single sensor that was not part of the setup initially.

Then it's completely pointless, you'll end up in the same situation as now most of the time - except worse since it's not consistent and you never know what to expect.

> If my voltage sensor is referenced (in display, LS etc.) as 030210 instead of index 4,

That can't happen without huge changes to the way everything works in OpenTX - so it won't. 

Once again when you make a copy of a setup as seems to be the main reason for complaining everything should work as is out of the box, so again we're losing time on a complete non-issue. You have both conveniently ignored responding to that argument.

**Comment by lshems** [comment]
Still relevant, and reports on crashes because of it have in the meantime become available.
