### ISSUE TITLE
OpenTX 2.2.1 - R9M (QX7) does not reflect current set bind mode

### ISSUE THREAD

**Issue by MartyHugh** [opentx/opentx#5592]
It is not possible to tell from the radio which mode is currently bound.   

First of all this information should be listed, but the only way of getting at it seems to be to enter [Bind] to bring up the bind mode selection menu.  I suggest that this is not a good way to review existing settings.

Secondly, and more of a concern, when the bind menu does appear, the selected mode is not necessarily the mode which is bound anyway.  On my radio it always shows the third option (500mW, 8Channel), despite the fact that I have 25mW + Telemetry (second option) bound.  This is confirmed by the fact that the radio is getting telemetry and this is the only mode which does get telemetry.

Thanks.

**Comment by 3djc** [comment]
There is no technical way to read that information from the R9M. In 2.2.1, it is purely a choice you make at binding time, and once it is done, that information is not kept.

There are some change in nightly that 'store' your last bind attempt', but it is still inperfect, because there is no guarante that you actually completed the binding; so it might be showing something that is not actual
