### ISSUE TITLE
Misbehaviour of GV's increment setting - X9D+, OpenTx 2.2.1

### ISSUE THREAD

**Issue by pindeslandes** [opentx/opentx#5602]
I set two Adjust GV special functions:
![vg1](https://user-images.githubusercontent.com/8396899/34647914-f911d9ae-f38f-11e7-8377-15e23bc2f444.PNG)

The GV limits are initially those (unmodified):
![vg1bis](https://user-images.githubusercontent.com/8396899/34647918-0c469da2-f390-11e7-8039-7da0d452e299.PNG)

It’s working fine: GV1 increases by 10 or -10 when pressing trim tab right or left.

Then I change the minimum value of GV1:
![vg2](https://user-images.githubusercontent.com/8396899/34647920-1dc09c90-f390-11e7-8d43-e7f2cf594c1d.PNG)

And going back to the SF tab, I see that:
![vg3](https://user-images.githubusercontent.com/8396899/34647926-2c1e0a8e-f390-11e7-9d30-1cd430d5f5bd.PNG)

The increments values have been modified but SF1 and SF2 are still working as intended: GV1 increase by 10 or -10 when pressing trim tab right or left.

**Comment by elecpower** [comment]
Same issue on radio

**Comment by Miami-Mike** [comment]
I'm not sure if you're aware of this problem and are working on it, or under the impression that it's been fixed, so I'll post it to this thread rather than open a new one:

In Companion 2.2.3, set a GV to Min = -1 and Max = +10.

Set a special function to increment that GV by +1 with RudTrim Right, and another special function to increment (actually decrement) it by -1 with RudTrim Left (or any other choice of switches).

That works. You can use the rudder trim to adjust the GV value up and down within the range of -1 to +10.

But suppose you only want to allow GV values from +1 to +10. Change the Min setting from -1 to +1 so that the GV limits are now Min = 1 and Max = 10. You should now be able to change the value up and down within the range of +1 to +10.

Now go back to the Special Functions page and you'll find that the function that you had set to -1 is now changed to +1 and can't be set below that value. You can no longer reduce the value of the GV using the Adjust GVx > Increment special function.
