### ISSUE TITLE
X9D+ on screen telemetry data seems to overflow

### ISSUE THREAD

**Issue by mpjf01** [opentx/opentx#5608]
[MODEL46-2018-01-08.csv.log](https://github.com/opentx/opentx/files/1610595/MODEL46-2018-01-08.csv.log)
![img_20180108_140651](https://user-images.githubusercontent.com/6133447/34658709-11e165c0-f481-11e7-889c-acad08202638.jpg)

As can be seen the fields seem to be overflowed in the bottom row. The three fields are meant to be Alt, Alt+ and Alt- from a second (HP) vario attached to a G-X8R receiver. the top row is altitudes from the inbuilt vario. 

The log file is also attached. Logging was only at 5s intervals so it may not be much help. The issue is repeatable, happens after about 15 minutes or so.

If the cause is bad data from the sensor, ie a FRSKY firmware or hardware problem, I'll report it to them.

**Comment by 3djc** [comment]
I do not think there is an issue with OpenTx display on that screen that could cause that. In the log attached, there is no abnormal Alta value (maybe because of the 5s log time), but the Vspa value are really  strange, periodicaly, you have either -10.2 or 10.2 changes that do not translate in either Alt or Alta changes, so it looks like your 'a' sensor is somewhat sending randomly bogus data

**Comment by mpjf01** [comment]
I redid the test with logging at 0.1s. There's a few examples there of weird altitude values that seemed to have caused the problem.
[MODEL46-2018-01-08.csv.log](https://github.com/opentx/opentx/files/1611051/MODEL46-2018-01-08.csv.log)

**Comment by mpjf01** [comment]
It's pretty clear to me that this is a FRSKY sensor issue not an OpenTx problem, so I will take it up with them. Sorry I bothered people here with it.
