### ISSUE TITLE
Feature Request - copy 

### ISSUE THREAD

**Issue by sjb0095** [opentx/opentx#5739]
Gents,

I would find it really helpful to be able to copy pages between models, example copying logical switches, or outputs..

make it so! :)

**Comment by 3djc** [comment]
The issue is that all things are related, logical switches depend on telemetry, or input, or mixers, and it is the same everywhere. You cannot copy/paste screen without breaking everything.

What many people do when they have things they like to be done a certain way is do a basic model that has those things are derive new models from it.
