### ISSUE TITLE
Failsafe issues when flying with another pilot on Nightly Build

### ISSUE THREAD

**Issue by trojanGoat** [opentx/opentx#5756]
My radio is the Horus X10 with opentx-companion-2.2.2N541
I have not experienced much failsafe issues with this radio except for today.  I noticed that it was a bit odd when all 3 quadcopters I brought with me were all having very frequent failsafe issues.  

After a few flight sessions, I realized that the failsafe only happened when my friend was powered up and flying at the same time as me.   Even with a short flight distance of 50 meters, failsafe issues would occur.

To confirm the issue we experimented with 2 scenarios:
1) Fly without the interfering transmitter/receiver powered up.  
- There were no issues when the other transmitter was off, which means the issue is not my hardware / antenna placement

2) Fly with the interfering transmitter and quadcopter beside me with the vtx powered off.
- Failsafe activated about 20 - 30 seconds into the flight.  

I'm not sure if this is an opentx issue or a frsky hardware issue, but we are both using nightly builds.  The other transmitter is a Taranis X9D
.

**Comment by 3djc** [comment]
First of all, nightly builds are not meant for flying, there is even a warning about it when starting.

That said,, OpenTX has nothing to do with the radio transmission itself. If you have interference, it cannot be because of OpenTX.

2.4 Ghz, radio systems (all brands , FrSky included) are extremely robust to concurent use, Hundreds of pilots at  the same place have been tested already without issues (but you did not say what kind of radio link you where using).

It is possible that a damaged electronic component somewhere in one of the radio/craft that where present is 'poluting' the whole RF spektrum, but I guess it needs to be found  by trial and error.
