### ISSUE TITLE
LUA lcd.drawPixmap() on X7(s)    y coordinate don't work

### ISSUE THREAD

**Issue by Morgan-T-fr** [opentx/opentx#5911]
ex : lcd.drawPixmap(4,Y,imgName1) 

only valid values for Y coordinate are : (1,8,16,24,32,40,48,56,64)
other values have no effect on image position

Best regards Morgan

**Comment by Morgan-T-fr** [comment]
No issue to draw img at à wanted positions ?

**Comment by raphaelcoeffic** [comment]
@MorganTr44 the issue here is that the framebuffer uses 1 bit per pixel, which means that it would require quite some shifting to write at a specific position. The draw routine is made to write into the frame buffer aligned on bytes, which is faster.

So, whereby it would be possible to "fix", this seems to me to be "by design", and as it is used everywhere, it would possibly move quite some stuff around on existing screens, which means re-testing and adjusting everything on these 1bit displays.

@bsongis should we really change that? Or offer a second function which is pixel exact just for LUA?

**Comment by raphaelcoeffic** [comment]
here is the function for reference:
```c++
void lcdDraw1bitBitmap(coord_t x, coord_t y, const uint8_t * img, uint8_t idx, LcdFlags att)
{
  const uint8_t * q = img;
  uint8_t w = *q++;
  uint8_t hb = ((*q++) + 7) / 8;
  bool inv = (att & INVERS) ? true : (att & BLINK ? BLINK_ON_PHASE : false);
  q += idx*w*hb;
  for (uint8_t yb = 0; yb < hb; yb++) {
    uint8_t *p = &displayBuf[(y / 8 + yb) * LCD_W + x];
    for (coord_t i=0; i<w; i++){
      uint8_t b = *q++;
      if (p < DISPLAY_END) {
        *p++ = inv ? ~b : b;
      }
    }
  }
}
```

**Comment by bsongis** [comment]
I think we should keep the optimization when we are aligned, but in all other cases we should do the right job

**Comment by raphaelcoeffic** [comment]
Please note that this might change the position on the screen of quite some items in the 128x64 res.

**Comment by bsongis** [comment]
If this is the case, we could add another function, just used by Lua (which would call the current function in case alignment is good)

**Comment by raphaelcoeffic** [comment]
yes, I'd really prefer that!

**Comment by raphaelcoeffic** [comment]
@MorganTr44 Could you please upload such a pixmap? at the moment, I get only garbage with the current code and a 1bit bitmap (24x40) produced with Gimp.
