### ISSUE TITLE
Curves copied from Companion 2.1.9 to Companion 2.2 can retain their 6 character names.

### ISSUE THREAD

**Issue by Miami-Mike** [opentx/opentx#6104]
When I copy a curve with a 6-character name from Companion 2.1.9 and paste it into Companion 2.2.2, the name is truncated to 3 characters on the Curves page but will show up on the Inputs or Mixes page, and on a Print Model printout, with its original 6-character name. This seems like a handy workaround for the inconvenient 3-character name limit for curves, but if it has the potential to cause a problem then I assume you'll want to fix it.

**Comment by kilrah** [comment]
It most likely gets truncated on save/export. That's when the specificities of a radio get taken into account, until then companion uses an internal format.

**Comment by Miami-Mike** [comment]
If that's the case then it's safe for me to keep the 6-character curve names without worrying about overwriting memory or causing some sort of malfunction, and my transferred model setups will be more legibly documented. And now I'm wondering if the same is true of other label length limits that were reduced for version 2.2.

But if it's safe to do that then why limit name lengths in Companion? For people like me who do all model creation and editing on my computer, it would be a tremendous improvement to be able to add virtually unlimited labels and comments to model setups and let them be automatically omitted or truncated as necessary when the setup is uploaded to the radio.

**Comment by mpaperno** [comment]
> why limit name lengths in Companion? 

Well if we don't then people (who do not understand) will wonder what happened to their nice long descriptive names once it transfers to the radio.  Plus the extra characters would get lost anyway if one imports back from the radio so ppl will complain about it (I realize not everyone does that).  Plus it (typically) ensures you don't name something with the same N leading characters so that once truncated two items would appear to have the same name on radio.  The list goes on, really....  Sure anyone who fully understands these limitations could benefit from what you suggest, but it would be at risk of alienating any "casual" or new users many of whom already think OTX is too complicated.  "Oh you didn't know the names were limited size on the actual radio?  jeez... what a newb!"   :)

**Comment by Miami-Mike** [comment]
Okay, got it. Thanks.
