### ISSUE TITLE
Flash bootloader is not available for Horus

### ISSUE THREAD

**Issue by notlebowski** [opentx/opentx#6128]
I noticed that "Flash bootloader" is not available on a X12S when I select a firmware-file using the SD-Card manager.
In the past this should not be available, but this has changed.
Is it as simple as a compiler directive that needs to be changed or does it need special coding that just not has been done?

It's not that I really need it.
It's an observation and maybe you're just not aware that it's not implemented yet.

**Comment by kilrah** [comment]
Known, needs to be coded.

**Comment by MikeBland** [comment]
I've "borrowed" the bootloader from openTx so I can use it with ersky9x (until I get my own bootloader working!). I have a "stub" in esky9x so I reserve 128K of flash for the bootloader, with code that just jumps to the main application.
I have the code to flash the bootloader in ersky9x (maintenance mode), so I tried flashing the bootloader from that. The flashing failed after writing 64K with the screen going blank, and then the radio didn't work unless I disconnected the power and even then, it would only operate in STM bootloader mode.

I deduced the time taken to erase flash sector 4 (64K) was longer than the watchdog timeout. Because the flash memory is erasing, no code is executing during the flash erase (unless the code is in the upper 1Mb of flash possibly), so software to extend the watchdog timeout doesn't work. I found I had to re-configure the watchdog to give a longer time to allow the sector erase to work, then the bootloader flashed successfully (and works OK flashing over USB).

It seems that if only the first 64K of the bootloader is flashed, it doesn't work, even for a normal power on without the trim switches pressed.

I would suggest the bootloader is therefore changed so the check for the trim switches and subsequent jump to the main application works even if only the first 16K of the bootloader is successfully flashed.
