### ISSUE TITLE
Throttle can be accidentally engaged while remapping controls

### ISSUE THREAD

**Issue by sup4rl33thax0r** [opentx/opentx#6185]
Tonight, I was completing the construction of my first plane.  Having finally gotten all the servos hooked to the appropriate control surfaces, I was trying to figure out how to map everything.  I was in the mapping screen, trying to figure out how to get everything set up, and accidentally assigned the aileron stick to the ESC channel.

Bad things happened.  Because the neutral position of the aileron stick is 50%, the motor immediately fired up.  Surprised, I instinctively reached for the model and my middle finger got in the way of the 10x4.5 prop which was now spinning at about 6,550 RPM.  It sliced my finger to the bone, taking a chunk out of the prop and breaking it in half.  1 ER visit and 5 stitches later, I have a permanent reminder of the dangers of rotating props attached to brushless motors.

Is there a way to keep this from happening?  Some sort of warning screen that indicates to the user that they're about to do something stupid?  Something that keeps the throttle from being mapped to a control that is set at > 0%?  Anything that will keep this from happening to someone else?

I have pics of the carnage but I'll spare you guys the pictures of high velocity blood spatter and fingers that don't look right.  Just want to keep this from happening to someone else.  Because everything happened faster than the speed of thought, this sort of accident needs to be avoided as early in the causal chain as possible.

**Comment by 3djc** [comment]
First rule of plane modeling : you remove the prop when you do work on your plane setup.
Second rule, you setup a motor cut switch 
Third rule, do not forget rule 1 !

Sorry to hear what happened, but there are so many ways things like that can happen that there is not realistic way of solving that (and not sure what you call mapping screen)

**Comment by mpaperno** [comment]
Very sorry to hear about your accident.  You're also somewhat fortunate because it could have been a lot worse.  And yes, you broke that 1st rule.  (No judgement here... I have a 2.5" scar on my hand where a prop tried to fillet a finger... and that was after a bunch of years of modelling, so I really knew better than to let it happen.)

The transmitter is a tool... it's like asking a hammer not to hurt your thumb when you miss the nail.  Sure you could use a soft hammer, but that won't be very effective for the intended purpose.  The "throttle" is just a channel... there's no way to know what is actually plugged into it at the Rx end.  And "something stupid" is a really wide-open specifications (and an unlimited capacity in humans :) ).
