### ISSUE TITLE
How to chose between SBUS or IBUS Turnigy 9x (OpentTX 2.1.9)

### ISSUE THREAD

**Issue by Ubishiro** [opentx/opentx#6222]
Hello,

I think it might be a noob question but with the original firmware in the Turnigy 9x v2, I can choose between SBUS and IBUS.

With the OPENTX 2.19 it works great but I can only use ibus and dont know were I can select SBUS.

Thanks for the help.

**Comment by kilrah** [comment]
If that is with the recent 9x with the new AFHDS2A module that would be a new possibility that did not exist with the old module at the time OpenTX 2.1.9 was released. I don't think anyone has reversed how the new module works at this point.
Since we do not support the 9x anymore it is unlikely this will be implemented in OpenTX.
