### ISSUE TITLE
CRSF Lua script doesn't fit QX7 screen

### ISSUE THREAD

**Issue by nmaggioni** [opentx/opentx#6287]
Issue #5165 is stale as the script has already been ported to the QX7, but its UI is terrible: the different display size from the X9D wasn't accounted for and most values go off screen to the right.

The device script should be revisited to give each value the most screen space available next to the key name - values such as the MAC address are really tough to fit on the X7's screen, just like longer Pilot or Craft names. In the meantime #6286 fixes the initial loading screen.

**To Reproduce**
1. Run the `crossfire.lua` script.
2. Connect a Crossfire-compatible module.
3. Enter one of the devices.
4. Notice that values overflow the screen.

**Screenshots**

![screen-2019-01-06-160617](https://user-images.githubusercontent.com/3594528/50737151-39a7b600-11c6-11e9-879b-ad7e6ecb98ab.png)

![screen-2019-01-06-160610](https://user-images.githubusercontent.com/3594528/50737153-3d3b3d00-11c6-11e9-9b5c-b4c15794be02.png)

**General information**
 - OpenTX v2.2.3 N683
 - FrSky Taranis QX7

**Comment by qral** [comment]
Still valid.


![missing2number](https://user-images.githubusercontent.com/74139/77554364-3fb2b100-6eb6-11ea-8e07-f5aa6244f3ee.png)
![SmartAu](https://user-images.githubusercontent.com/74139/77554368-404b4780-6eb6-11ea-8454-2a703f8400ae.png)

**General information**
<pre>
OpenTX v2.3.5 (db7d2413)
FrSky Taranis QX7 
</pre>

**Comment by jforhan** [comment]
Looking at the scripts real quick, I don't believe it is a function of the script. The text strings are received from the TBS module then displayed. Since I don't think you can scale the font on the Taranis LCD screen there is no easy way to do it.

Even my Horus X10s Express has issues. Some of the text is cut off. That may be a script issue of not getting the entire string from the TBS. (I.e. "Do not interru" vs "Do not interrupt" ). There are also other issues with the X10s Express like random characters when RX is updating and non-consistent display updates.

Jeff
