### ISSUE TITLE
Mega2560 2.2 Support

### ISSUE THREAD

**Issue by davidbitton** [opentx/opentx#6317]
The radios page on the site states that the Mega2560 support stopped at 2.1 however the 2560 is still in the targets folder for the 2.2 branch. So, which is correct?

**Comment by 3djc** [comment]
Support has been removed in 2.2. The (partially non functionning) code is still present in 2.2 but we do not compile firmware with it anymore, and has been removed in 2.3 branch.

**Comment by davidbitton** [comment]
Is there any support for a "non-radio"? I have a need to develop a custom solution that I'd like to use OpenTX in.

**Comment by kilrah** [comment]
Well the code is pretty modular so that you can add support for any hardware you wish.

**Comment by davidbitton** [comment]
except the Mega2560. OK, how about a SAMD51?

**Comment by kilrah** [comment]
You can run the 2.1 code on a 2560. You can fix the 2560 support in the 2.2 code if you wish. You can add back 2560 support in 2.3 and run it on your custom stuff if you wish. That's what open source is for... it's not because **we** decided not to keep supporting a platform that none of us still has and no-one has offered to maintain in a couple of years and thus we couldn't vouch for the quality of what we're distributing for it that you can't do it yourself.

**Comment by davidbitton** [comment]
ok. what's "broken" with the 2.2 code? i can take a stab at it.

**Comment by kilrah** [comment]
Been a long time, don't really remember. I think it was data exchange with companion.

**Comment by davidbitton** [comment]
Is there a reference  hardware implementation? The Taranis is an STM32, right? Maybe I could use a DisoveryF4 board as the MCU

**Comment by 3djc** [comment]
STM32 is for sure an easier choice, since most currently supported radio run STM32. AVR radio where phased out by lack of dev/user support, but also because of hardware limits that prevented new features to be developped for that platform since 2.1.

**Comment by davidbitton** [comment]
I should be able to figure out pin assignments from one of the `board.h` files.

**Comment by kilrah** [comment]
For pins you actually mostly want to look at `hal.h`.

**Comment by schwabe** [comment]
And of course here: https://github.com/opentx/opentx/tree/2.2/doc/Mega2560
