### ISSUE TITLE
Taranis 9X Lite Wheel issue 2.3.0N40

### ISSUE THREAD

**Issue by PonyOny** [opentx/opentx#6551]
On occasions when you turn on the Taranis 9x Lite the wheel button will not work when rolling, it will only click, you have to restart the radio several times until the wheel works correctly and allows you to navigate up & down through menus.

 - OpenTX version: 2.3.0N40
 - Hardware: Taranis 9X Lite
 - OpenTX Companion: 2.3.0N39

**Comment by P-I-Engineer** [comment]
same for me

**Comment by bsongis** [comment]
I am searching for a possible cause, I never encountered it on my end

**Comment by bsongis** [comment]
I found something funny, if you turn the wheel during the startup sequence, the radio will shutdown instead of start

**Comment by P-I-Engineer** [comment]
N41 seems to be working

**Comment by Harpalyke** [comment]
I also have this issue with my x9lite. Started to notice it when I flashed N33 a couple of weeks ago but I didn't get the chance to update the firmware since.

I've tried the N41 build and it still seems to be a problem on my radio. It's not happening as frequently as N33 though, I was seeing it happen about 8 out of 10 times before. 

One thing that I have noticed is that when it boots and the scroll wheel isn't working if I leave the radio idle for a minute or so the scroll wheel then works again.

I had thought it might have possibly been a hardware issue at first but the scroll wheel always seems to work in the bootloader menu so I'm guessing it probably is an issue on the software side.

**Comment by bsongis** [comment]
Is it possible one of you contact me by email. I think the debounce delay value I chose is not optimal on some radios, I would like to check which is the value which would work for you.

**Comment by bsongis** [comment]
Unless there is a race condition on init, please download the next nightly build, I hope it's not too late, nightly build should start around now

**Comment by P-I-Engineer** [comment]
will do tonight, thanks

**Comment by Harpalyke** [comment]
Seems to have done the trick. I rebooted the radio about 10 times in a row and the scroll wheel is now responsive 100% of the time after it boots. Thanks.

**Comment by glideasw28** [comment]
I have the exact same issue as "Harpalyke" above. Not using nightly though. 
Running official firmware update from frsky (2019-06-26) 2.3.0
Scroll works one in ten starts. Scroll will work if left idle for a minute.

Thanks.

**Comment by bsongis** [comment]
@Harpalyke would you confirm that the issue was fixed between N41 and N42?

**Comment by P-I-Engineer** [comment]
N44 is working

**Comment by Harpalyke** [comment]
@bsongis, yep, seems fine on my radio now also.
