### ISSUE TITLE
[call for review] updated wiki, docker build instructions

### ISSUE THREAD

**Issue by nitram509** [opentx/opentx#6624]
Hi,

I did create a wiki page on how to compile the firmware using the docker image.
This is a great way for many developers since it works without preparing all the required tools and results in reliable builds.

Because I'm not a native English speaker, I would like to kindly ask for review/feedback of this page:
https://github.com/opentx/opentx/wiki/OpenTX-Docker-Build-Instructions

Regards
Martin

**Comment by lshems** [comment]
I, as many others, cannot use docker as it is not free?

**Comment by raphaelcoeffic** [comment]
> I, as many others, cannot use docker as it is not free?

@lshems  why do you think it's not free? I'm using it every day, and it's open source with project Moby.

Just from a very quick search (1s):
```
Docker Desktop for Windows is available for free. Requires Microsoft Windows 10 Professional or Enterprise 64-bit. For previous versions get Docker Toolbox.
Docker Desktop for Windows - Docker Hub

https://hub.docker.com/editions/community/docker-ce-desktop-windows
```

**Comment by raphaelcoeffic** [comment]
@nitram509 I haven't tried it out myself, but you might use the same mount path for both commands, as some might think it should different when executing `cmake` and then with `make`. It could be a good idea as well to add some instructions for windows (mount path is different).

**Comment by elecpower** [comment]
@nitram509 my suggestions

- avoid abbreviations e.g. _configuration_ instead of _config_ to help in text translations
- add the applicable Open Tx version(s) to the page title as the instructions can change between versions
- I know this should not be the case but based on previous misunderstandings, the instructions need to be clearly sequential and for multiple operating systems
- make prerequisites its own section
- add a link to the main Docker site so responsibility for installing and current legal use is up to the individual

Introduction

- _This little tutorial_ suggest _These instructions_
- typo _radion_ should be _radio_

**build docker image**

- change _tooling_ to _tool chain_ for consistency with other parts of the Wiki
- add a link to the how to create a local clone of the Open Tx repo (move to prerequisites?)

**Build the firmware**

- as @raphaelcoeffic 
- how to transfer the newly compiled firmware onto the radio. You would be surprised how many do not know how to do this.

Thank you for the effort

**Comment by nitram509** [comment]
Thank you @raphaelcoeffic @elecpower  for your feedback. 👍 
I did update the page accordingly.

If there's nothing left to say ... thank you and please close this issue :)

**Comment by lshems** [comment]
About the opensource aspect of docker.

I was deviated to the paid version, as happens with so many opensource projects, had to register, only to find out only for companies?

I'll try and find the opensource version.

**Comment by raphaelcoeffic** [comment]
It's called "community edition" ("ce").

**Comment by raphaelcoeffic** [comment]
@nitram509 I guess we’re done here? Let’s close then.

**Comment by nitram509** [comment]
@raphaelcoeffic can be closed, yes.
Thank you all for you support.

**Comment by raphaelcoeffic** [comment]
@nitram509 the page looks like it has disappeared. What happened?

**Comment by kilrah** [comment]
For some reason he renamed it, so it broke existing links... https://github.com/opentx/opentx/wiki/OpenTX-2.3-Docker-Build-Instructions

**Comment by nitram509** [comment]
@raphaelcoeffic I renamed the page, because of feedback (see above)
"add the applicable Open Tx version(s) to the page title as the instructions can change between versions".

**Comment by kilrah** [comment]
OK, the index page wasn't updated for it though. Just did that.
