### ISSUE TITLE
OTX 2.3 Nightly, X9D+: Not enough memory on device

### ISSUE THREAD

**Issue by RipperDrone** [opentx/opentx#6672]
When trying to download Taranis FW through OTX Companion Nightly 2.3 (PC = Win10 x64), the 'Downloading...' dialog box stays on the screen for ~30secs with no progress, then says there is not enough memory available on device. 

I have ~50 models on my Taranis, ~1000 bytes free mem space shown on OTX 2.2.3. I thought that model memory and FW memory are non-shared so this shouldn't matter?

**Comment by kilrah** [comment]
Is the error on the radio or the PC? If on the PC you're probably trying to save the file to a location you don't have permission to write to or no space left. It's normal for nightly builds to take several minutes to download, the build process is slow. 

Also once you have flashed the radio with 1000 bytes free the 2.2->2.3  model conversion is likely to fail since it needs free memory that is at least somewhat bigger than your biggest model to hold a temporary copy, and all models will take a bit more space after the upgrade.
