### ISSUE TITLE
RX #: false positive "same number" detection

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#6765]
Looks like the RX number detection doesn't make any difference of which module is used.

In the example below (red & blue rectangles), Companion doesn't make the difference between the internal XJT module and the external multi module.
![tmp](https://user-images.githubusercontent.com/1685030/64860330-1ffc1f80-d62d-11e9-828f-f98249a514c2.png)

**Comment by 3djc** [comment]
fixed in rc2

**Comment by notlebowski** [comment]
Please reopen:

I have this in RC3

These models have RxNum #1 

#3  Kinetic  D16
#12 Me109 Multiprotocol
#15 Corsair D8

#15 and #3 are false positives. The Kinetic uses a D16 protocol and the #15 Corsair uses D8
The #12 (Me 109) is indeed not flagged anymore as a duplicate because it's another module
![rxnum](https://user-images.githubusercontent.com/39838998/64911174-92006180-d71e-11e9-8ed1-f2514e9c0828.JPG)
