### ISSUE TITLE
Companion telemetry conversion 2.3.0RC5

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#6819]
Rechecked the conversion after #6798 fixed and noticed the following changes from 2.2.4 otx but not sure if a conversion issue or the way data will be displayed in 2.3.

Version 2.2.4
![otx224telemetry](https://user-images.githubusercontent.com/15316949/65463712-9ace0180-de9b-11e9-9c07-9c90bc4d4a7a.png)
Version 2.3.0RC5
![Screenshot from 2019-09-24 07-13-00](https://user-images.githubusercontent.com/15316949/65463726-a15c7900-de9b-11e9-8d0d-f7d3e2866d9f.png)

My 2.2.4 flashed X9D+ radio displays the same as the Companion 2.2.4 screenshot.

**General information**
 - Hardware Frsky X9D+
 - OpenTX Companion 2.3.0RC5 on Ubuntu 16.04

**Comment by raphaelcoeffic** [comment]
The instance does now correspond to what is actually received. In 2.2.4, it was +1, so the instance was actually wrong and has now been corrected. So it is in fact fully intentional.

Concerning the `()` you can see behind the sensor name in sources, this would contain the name of the receiver in case you would select a specific one and would be using ACCESS. This is very similar to the way this is displayed on the radio.

**Comment by elecpower** [comment]
@raphaelcoeffic thanks for the explanation. Just wanted to double check. I do not have a spare radio to test the firmware on so couldn't check what the radio displays in 2.3.0RC5 to make sure Companion matches for the Instances. Happy to close.
