### ISSUE TITLE
2.3 not allowing .frsk file flashing on older radio

### ISSUE THREAD

**Issue by anthsorr** [opentx/opentx#6893]
2.3 is not allowing .frsk files to be loaded on R9MM-OTA via the rear port of the Taranis X9D+SE. Can this be addressed?

**Comment by 3djc** [comment]
Please try 2.3.1N7 that will be available later today

**Comment by fjp** [comment]
@3djc I have a similar issue with the Taranis X9D+SE using 2.3.2N41. I was able to flash the R-XSR with the latest FPort firmware (`R-XSR_FPORT_LBT_190311.frk`). However, I cannot flash the latest ACCESS firmware `RXSR-FPORT_ACCESS_191107.frsk`. When I long press the file name, I only get the following options:

```
Flash S.Port device
Flash Receiver OTA
Copy
Rename
Delete
```

There is no option to `Flash external module` as it was the case with the `*.frk` file.

Is this a problem with openTX? 

What is the difference between the `*.frk` file and `*.frsk` file?

**Comment by bsongis** [comment]
.frsk files have a header which tells to the radio which is the destination. If your .frsk is a firmware for a receiver it won't be possible to flash it to the module by mistake

**Comment by fjp** [comment]
When I try to update the firmware (`RXSR-FPORT_ACCESS_191107.frsk`) I get the following error message:

```
Firmware update error
Device not responding
[EXIT]
```

I also tried the S.Port firmware (both *.frk and *.frsk). *.frk works but I don't know how to use the *.frsk file or if it is even needed.

**Comment by fjp** [comment]
> .frsk files have a header which tells to the radio which is the destination. If your .frsk is a firmware for a receiver it won't be possible to flash it to the module by mistake

@bsongis thanks for the information. Does this mean that with *.frsk files it is only possible to flash internal modules and no receivers like the R-XSR? 

I saw that .frsk firmware files should be supported in 2.3.0. 

> Support for .frsk firmware files. Those contains identification of target hardware, preventing flashing wrong device with wrong firmware type errors

Is there anything else I need to do in order to flash the .frsk firmware to the R-XSR receiver via the rear port of the Taranis X9D+SE? Thank you for your help.

**Comment by kilrah** [comment]
Which X9D+ do you have? The 2019 or old version? 2019 should show the choices you have, and older "Flash external module" instead. Code looks correct.

**Comment by fjp** [comment]
I use the Taranis X9D+ 2019 SE. So it shouldn't make any difference flashing .frk or .frsk? Both should work? Thanks for the support.

**Comment by kilrah** [comment]
2019 has a sport connector like the menu suggests so you must use that, not the module pins.

**Comment by fjp** [comment]
Thanks, I wasn't aware of that S.Port where the battery  is located. I will try flashing with that S.Port.

**Comment by fjp** [comment]
@kilrah thank you again for the hint. Flashing the .frsk file worked using the S.Port. Is there a manual where I could've read about this S.Port? I followed too many tutorials for the X9D plus (not the 2019) version. I now also noticed the S.Port in the official [manual](https://www.frsky-rc.com/wp-content/uploads/Downloads/Manual/X9DP2019/X9D%20Plus%202019%20X9D%20Plus%20SE%202019-Manual.pdf). Are there any other important resources regarding flashing with opentx and the Taranis X9D Plus SE 2019?

**Comment by kilrah** [comment]
It's there, if you want to flash a device you connect it and select flash. Nothing fancy.

**Comment by gnkarn** [comment]
Hi all , i have taranis XD9 plus , old model , with 2.3 firmware and trying to flash an XSR receiver , because telemetry is not working and i have no clue what firmware version is on it from factory .
I was unable to flash it using pack port, i see that mine has also a "reserved" port  , is a three pin one , more like an sport , anyone one knows if , that one is anabled as an sport , when using newer  transmitter firmware like the one i have now ? ,  thank you

**Comment by kilrah** [comment]
No it's not, you have to use the module pins and the cable with swapped pins

**Comment by gnkarn** [comment]
that is what i did, not working ( and works fine with other modules like Frsky X8R , any recommendations of what else to try ,  other firmware version on the taranis? , already tried with 2.1 also , tis

**Comment by 3djc** [comment]
If it works with X8R, it means radio+firmware+cable is ok, issue with your XSR or its connection

**Comment by gnkarn** [comment]
by looking at the serigraph on the board it says X4RS rev 1.1  could it be possible that they installed the wrong firmware , I suspect of something in that line, because  radio controls work fine , then when trying to flash it makes the reset right , by then the taranis says " update error device not responding "

**Comment by gnkarn** [comment]
HAVE a doubt now , not related to receiver not flashing . :  i do have connected rx6: sbus , and Tx6 to Sport , on my kakute F7 ,  is that correct ? , or should i use a different port for telemetry , than radio ? , thanks

**Comment by 3djc** [comment]
Your receiver must NOT be connected to anything else when flashing

**Comment by gnkarn** [comment]
sure ,  my RX is not  flushing  , so gave up on that part  for the moment , need to move on .

what  i m asking is  if when using both wires ( separate rx and telemetry) ,  the connection can be on the same port (like  RX6,Tx6) , or do i need to use different ports ( RX1, TX6) , i red many cases when people with no telemetry  were moving to serial1 , for sport to work .. tks
