### ISSUE TITLE
X9D RS not available, instead (non working) S3 shown in hardware

### ISSUE THREAD

**Issue by wilco1967** [opentx/opentx#6903]
Taranis X9D (non plus)
OpenTx 2.3.1 (5-oct-2019)

The right slider (RS) seems to be missing / not configured in the latest OpenTX for X9D

instead of RS, in radio settings / hardware menu an S3 Slider is shown, but that doesn't respond to anything.

same behaviour in the simulator, but seems correct in Companion radio settings.

**Comment by 483917** [comment]
Yes same for mee

Taranis X9D (non plus)
OpenTx 2.3.1 ,-haptic -flexr9m -sqt5font -lua -en

The right slider (RS) seems to be missing / not configured in the latest OpenTX for X9D

instead of RS, in radio settings / hardware menu an S3 Slider is shown, but that doesn't respond to anything.

switching back to OpenTx 2.3.0 firmware and (RS) is back

**Comment by dev-fred** [comment]
Was OK in 2.3.1N2 and appears in 2.3.1N3

**Comment by 3djc** [comment]
Fixed already

**Comment by wilco1967** [comment]
Seems to work !

Thanks !
