### ISSUE TITLE
OpenTX 2.3.2.N25 issue with external module simulator for T16

### ISSUE THREAD

**Issue by backman8571** [opentx/opentx#6989]
I installed N25 load and it only gives me 6 channels for DSM/X for T16

1 open the radio simulator

2, select external model

3. select DSM and D11/22 or X11/22

4. go to select channel range it will only allow upto 6 channels

**Expected behavior**
The radio should allow 12 or 16 channels

**General information**
 - OpenTX version2.3.2 N25
 - Hardware Jumper T16Pro Plus
 - OpenTX Companion on Windows 10

**Comment by 3djc** [comment]
Are you talking on the radio ? simu ? companion ? I get 12 on the radio as shown bellow

![image](https://user-images.githubusercontent.com/5167938/67361616-8009ae00-f569-11e9-823d-62b3b887c7a6.png)

**Comment by MRC3742** [comment]
Are you possibly selecting "DSM2" as protocol instead of "MULTI" and then "DSM" as sub protocol?

DSM2 Protocol is for the earlier DSM Hack module and only had six channels available.

**Comment by MRC3742** [comment]
@3djc  The problem is definitely in Companion 2.3.2N25 - T16

Setting the DIY Multiprotocol Module on either Internal or External and Protocol to DSM, any of the sub protocol choices originally show "6" under channels value . 
This channel value can only be changed from 6 to a value of 4, 5, or 6.

Using just the radio it works properly.
When DSM is selected, Channel Range shows CH1-CH7 and now can be changed to any value from CH4 to CH12 .

EDIT: More problems found listed below.
Setting up a model in Companion and leaving the default Channels "6" and writing to radio now causes Radio to show CH1-CH16 ? Trying to change in Radio CH16 immediately drops to CH12, CH11, CH10, etc. down to CH4 or back up and stops at CH12.

This may be the problem some are having with MULTI - DSM as the change of number of channels when writing from Companion to Radio will surely disrupt this Protocol from working properly?

**Comment by 3djc** [comment]
Thanks @MRC3742 , with a proper description of the issue, i was able to fix it :)
