### ISSUE TITLE
RSSI source in Telemetry is no longer available

### ISSUE THREAD

**Issue by dposea** [opentx/opentx#7035]
I changed some option by editing RSSI, and now I get no sensors at all. RxBT and RSSI used to be always discovered. I'm not sure what to do now. Should I start a new model, restore the EEPROM?
I also no longer can select RSSI on the Inputs Source field.

Running Opentx 2.3.1 on a Taranis QX7.

**Comment by dposea** [comment]
Update, I started a new model and had the same problem until I rebound the R-XSR receiver. Only default and External were available in RSSI source, but I was using the internal module. It works on default, but Internal should be a valid choice, and External really should not be unless it is enable in model setup.

**Comment by al21883** [comment]
I have the same issue.
Can't select any source for RSSI on the telemetry page, except "(default)"
In my case, it's necessary to change the source, because I'm flying an old Hubsan H107D, and it only reports TRSS.
I have tried to delete the RSSI sensor that is reporting 0 but same result.

Running 2.3.9 on a TX16S

**Comment by kilrah** [comment]
This is to select the source for the built in RSSI handling, which only supports RSSI so selecting TRSS would do you no good. Just set your own alarms with special functions.
