### ISSUE TITLE
OpenTX build instructions using QT not working for 2.3

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#7174]
I do get to clone the 2.3 default branche locally, compile it with 'release' 'companion'.

it compiles, but the DLL files to run the resulting companion.exe seem to fail (are not there, not like they are faulty)

Any help appréciated

**Comment by MRC3742** [comment]
This is the same issue I believe that I reported on Issue #6831

If you first install one of the nightly Companion 2.3 builds and then copy in (over) the files that you get from the compile build it will then work properly.

There are some other compiling problems using Qt that I will open in a separate issue.

Hope this helps - Rich

**Comment by lshems** [comment]
thanks. I will check.

**Comment by zyren** [comment]
You need install python-clang

**Comment by MRC3742** [comment]
python-clang binding is only needed to build firmware as discussed in #7176 

Rich

**Comment by lshems** [comment]
I tried to copy over a clean nightly install. No good, still missing DLL.

It is rather frustrating that after five years of spending several hours everytime I want to contribute something, I get blocked at not being able to compile.

It is really not inviting anyone to get into this, when you want to get started with no experience on something small.

I just want to copy some functionality already in the mix lua api to the inputs lua api. Seems doable for me.

But not without a working compile possibility?

Please try to put some effort in getting this sorted out.

**Comment by dwheel** [comment]
I am building with MinGW 32 bit. In the build settings, it points to where the dll files are located. In my case, they are in C:\Qt\5.12.2\mingw73_32\bin. Run companion.exe and when it reports the dlls missing, go to this folder and copy then over to the companion.exe build folder. 

It would be nice if they were automatically copied over, but since they are not, this is a work around. 

Here is a print screen showing where to look.

![dll folder](https://user-images.githubusercontent.com/6865267/71191004-3678cf00-224b-11ea-8a1c-accb824f47ed.jpg)

**Comment by lshems** [comment]
Thanks a lot for helping out a noob. this was what is missing.

I can now see if I can add some work.

:)
