### ISSUE TITLE
Frsky x-lite trainer option missing

### ISSUE THREAD

**Issue by matthewthorp** [opentx/opentx#7488]
Trainer option in the model menu missing from opentx. I've recently bought a Bluetooth module to add to it as in this video.
https://www.youtube.com/watch?v=fyT6XohZIsY&t=478s

Gone through version history and seems to be showing last in v2.2.2

General information
 - OpenTX version 2.3.7
 - Hardware Frsky x-lite
 - OpenTX Companion 2.3.7 on windows

**Comment by kilrah** [comment]
Did you add your module yet? If the module isn't detected the relevant settings are hidden.

**Comment by matthewthorp** [comment]
Haven't yet, but it won't even show up in companion.

**Comment by 3djc** [comment]
No it does not show in companion because most x-lite do not have this mod, and if we where showing it, then people would either complain or assume their radio is supposed to have it.

So best course of action is installing it in your radio, it should get detected and relevant menu appear on your radio (and no companion will still not show it for the reason above)
