### ISSUE TITLE
trainer signal lost on T16 - opentx 2.3.7

### ISSUE THREAD

**Issue by JCPDE74** [opentx/opentx#7510]
"Trainer signal lost" being triggered multiple times in a few minutes. Cannot pinpoint what is triggering it. Release 2.3.7 Thanks for investigating it.

**Comment by kilrah** [comment]
Can't investigate much without knowing what you set the trainer settings to, what modules you're using etc...

**Comment by JCPDE74** [comment]
Hi Andre. I did not played with anything. Sd Card zeroed out, firmware
flashed and voilá... "trainer signal lost" started to be triggered.

**Comment by JCPDE74** [comment]
I'm using the radio on a simulator. Internal / external modules off (stock configuration)

**Comment by 3djc** [comment]
Then why did you setup trainer on this model ? Please join otx and specify which model you are using

**Comment by JCPDE74** [comment]
That is the thing... I did not set up trainer on this model. 
I was looking how to disable it and found that on the Jumper T16 (I guess in other radios too), there are 3 modes for trainer - master/jack, slave/jack,master/multi, but there is not a "off" selection available.

**Comment by JCPDE74** [comment]
Thank you for helping me. I appreciate your efforts

**Comment by kilrah** [comment]
If you set to slave it will output a signal and thus not check for an incoming one...

**Comment by JCPDE74** [comment]
Thank you Andre. I followed you recommendation, made a couple of flight and
it is working without warnings to this moment.

Maybe this should be the default setting when loading the software on the
radio.

**Comment by Nihonski** [comment]
check this: https://github.com/opentx/opentx/issues/8513
There is a signal conflict/crash on the heartbeat signal

**Comment by Cpt-Huck** [comment]
FlySky Nirvana 14 (NV14) - EdgeTX 2.7.1
just had this when writing an Backup via EdgeTX Configurator to my Radio.
If I go to "Model Setup" - scroll all the way down - and on "Trainer" - "Mode" - "Master Jack" is the default I guess ?!
Gives me the same problem you have "Trainer Signal Lost / Recovered". (Random ?! and when navigating through the menu ?!)
"Master/Multi" = no problems. But I just turned it "OFF" since im not using it. = Problem solved / fixed with this Setting.

**Comment by Nihonski** [comment]
If this issue is not solved yet, the HW might get damaged, as the Heartbeat signal driver shorts the SBUS signal, when the timing matches.
And of course the trainer does not work properly.
See the picture with SBUS signal pulled down vor about 0,4ms (heartbeat width.)


![118843439-5aba5e80-b8ca-11eb-86b8-923dc0693bf7](https://user-images.githubusercontent.com/14869213/174445173-213796df-ecb0-4d63-8405-c50c3aaf1bc3.JPG)
.
