### ISSUE TITLE
Flight mode transition bug

### ISSUE THREAD

**Issue by pmackenzie** [opentx/opentx#7623]
Another RCG user posted a problem he was having.
I looked at his OTX, and it seems like a bug to me in how flight mode transitions are done when a mixer channel is over +/-200.  The value changes sign and is offset by the difference from 200 during the transition.

Simple OTX attached, only one mixer line and one flight mode.  Channel value changes sign during flight mode transition, even though flight mode change should not affect its value at all.

**Comment by pmackenzie** [comment]
I don't see the attachment, above so here is a link to it on RCG
https://www.rcgroups.com/forums/showpost.php?p=44586343&postcount=2521

**Comment by mpjf01** [comment]
Seen this before .......but where? Maybe closed issue?

**Comment by dgatf** [comment]
@bsongis, weights over 200 is causing _sum_chans512_ overflows at the mixer when changing the flight mode. If we want to catch that, not sure which is the best option:

- Limit _chans_ value
- Decrease GV_RANGE_WEIGHT to 200. Is there a reason to have max weight up to 500? But still gvar could go up to 1024
- Decrease MAX_ACT from ffff to 3fff. This increases the maximum error in fade in/out duration from 1 to 4.2s (if I understood it correctly) due to _delta_ truncation
- Change sum_chans512 to int64_t. Increases ram usage by 1kb and increases Tmix max from 0.45ms to 0.50ms (I guess this is max mixer processing time)

**Comment by 3djc** [comment]
To be fixed in 2.3.10
