### ISSUE TITLE
Crash when you select others model at 2.3.0

### ISSUE THREAD

**Issue by JoshuaShaw** [opentx/opentx#7772]
Version: 2.3.9

Here is the bug video.

bug 01:  There are some errors when I upload firmware to 9xr pro.
[gif of bug 01](http://easyexcelif.com/images/bug.01.gif)

bug 02: When I set the external RF = XJT16, opentx crash
bug 03: When I select other model from the model that be setting external RF=XJT 8, opentx crash
[gif of bug 02 and bug 03](http://easyexcelif.com/images/bug.02.gif)

**Comment by JoshuaShaw** [comment]
[http://easyexcelif.com/images/bug.01.gif](http://easyexcelif.com/images/bug.01.gif)

**Comment by AlexDaniel** [comment]
Sorry, but I have the same issue, I think, and it is not resolved. In fact, my 9XR Pro has been bricked for quite a while because of this. I tried updating to a nightly version which I believe has https://github.com/opentx/opentx/pull/7775 but it does not fix the issue.

Basically, I was looking through the settings and had an unfortunate idea to select XJT in External RF. Now my transmitter is essentially bricked. If I try to change XJT to something else it immediately crashes and the setting remains. If I try to select another model then it crashes too. I can't figure out a way to get out of this situation. Connecting the transmitter to PC never really worked for me, so I can't change the setting from there. What do I do?

**Comment by pfeerick** [comment]
This is indeed not resolved - 2.3.11 still has the same 'instant crash' on the Turnigy 9XR-PRO when choosing XJT as the external module, or changing from it if you have it configured already in a memory. This is similar to #7594. 

It appears it may be somewhat specific to the XJT RF module option , but I have been able to get the transmitter to lock up when choosing PPM also. It seemed quite stable in limited testing if DSM2 or MULTI were selected. And as soon as you had a model with XJT as the external RF module type, you cannot switch out of the model either without a watchdog crash.

Transmitter crashes with an exclamation on the top right, and watchdog listed in the debug screen. It also powers up with exclamation mark and 'unexpected shutdown' listed in the debug screen.

**Comment by BrettRD** [comment]
This is not fixed in 2.3.11 on the 9xr-pro.
The only way out I found was to use companion to delete the model.

In my case, when I opened it in companion, the offending model had red text in the RX# column. Companion complained something about "source - ???" when I tried to write back to the radio after selecting PPM.
I can't seem to replicate the problem companion couldn't solve, but maybe that symptom is meaningful (corrupted data structure?).

Fiddling with this I was able to also trigger https://github.com/opentx/opentx/issues/7594

Also:
Duplicating a model, setting external RF `OFF` on one and `PPM` on the other, and switching to the `OFF` model causes a crash after 5 seconds.  changing from `PPM` to `OFF` works if you shutdown the handset before the timeout.
