### ISSUE TITLE
Companion: "Print model" of analog sensor prints the range wrong if precision is other than 1 digit

### ISSUE THREAD

**Issue by notlebowski** [opentx/opentx#8035]
I want to use the analog sensor for RSSI. After discovery of the A2 I change its range to 100 and the unit to dB.
![image](https://user-images.githubusercontent.com/39838998/95950352-a36dde80-0df4-11eb-87d5-70487b6d4974.png)
The print model then gives me this.

TELE6:2RSS Custom Id: F103 Inst: 27 Unit: dB Prec: 1 Ratio: **100** Offset: 0 A/Offset: N Filter: Y Positive: N Log: Y 

This looks fine, but when I change the precision to 0 decimals the print model reports a range of 1000 even though I selected 100

![image](https://user-images.githubusercontent.com/39838998/95950563-12e3ce00-0df5-11eb-8a73-db41cfcf5f78.png)

TELE6:2RSS Custom Id: F103 Inst: 27 Unit: dB Prec: 0 Ratio: **1000** Offset: 0 A/Offset: N Filter: Y Positive: N Log: Y

**Comment by aeronaut999** [comment]
There are some weird things about Precision Settings in OpenTx-- see https://github.com/opentx/opentx/issues/7949 -- maybe you've found another one.

Which version of "Companion" you are using?

You mean "ratio" instead of "range", right?

I just replicated your problem on Companion 2.3.9.  It's not unique to RSSI.  I saw it with other sensors as well.

More generally, we can see that-- on Companion--  for any telemetry sensor with a non-zero "Ratio" --

Regardless of the initial Precision Setting of a telemetry sensor, if we change the Precision Setting of the sensor, there will be no change in the "Ratio" shown on the "Editing Model-- Telemetry" screen, but the "Ratio" shown on the "Print Model" screen will change by a factor of 10.

Regardless of whether we've _changed_  the Precision Setting of some telemetry sensors or simply uploaded a model program where various telemetry sensors had various Precision Settings to start with, we can observe  that:

If a telemetry sensory has Precision Setting of 0._, the "Ratio" shown on the "Print Model" screen will be 10 times the "Ratio" shown on the "Editing Model-- Telemetry" screen.

If a telemetry sensory has Precision Setting of 0.0, the "Ratio" shown on the "Print Model" screen will be the same as the "Ratio" shown on the "Editing Model-- Telemetry" screen.

If a telemetry sensory has Precision Setting of 0.00, the "Ratio" shown on the "Print Model" screen will be one tenth of  the "Ratio" shown on the "Editing Model-- Telemetry" screen.

When I program directly on my Taranis Plus radio (OpenTx 2.3.9), changing the "Precision Setting" of a telemetry sensor doesn't change the "Ratio" of that sensor, so it appears that the "Print Model" function on Companion is getting it wrong.

When I use Companion to upload an OTX file to the radio, then when I go to edit the telemetry sensors directly on the radio itself, not using Companion, the "Ratios" I see on the telemetry sensors are the ones that match the "Editing Model-- Telemetry" screen on Companion, not the ones that appear on "Print Model" on Companion.  _Also, when we look directly at the radio itself, we can see that the actual returned value of a telemetry sensor stays the same (except for the number of decimal places) no matter what the "Precision Setting" of the telemetry setting is set to.  Rather than changing by an order of magnitude._

So it appears that the "Print Model" function on Companion is getting it wrong.

Another issue is that a ratio which is shown as "-" on the radio screen (at least on my Taranis Plus) is shown as "0" on Companion.  A "zero" ratio makes no sense and implies that the telemetry sensor should always return a value of zero.  What is actually going on is apparently that some automatically pre-set ratio is being applied.  It would be better if this were shown as "-" in Companion.

Related discussion about "Ratios" of telemetry sensors on RC groups: https://www.rcgroups.com/forums/showpost.php?p=45655441&postcount=3627 and subsequent replies.  Some of the subsequent replies such as 3631 https://www.rcgroups.com/forums/showpost.php?p=45660425&postcount=3631 and 3640 https://www.rcgroups.com/forums/showpost.php?p=45662817&postcount=3640 shed some light on why a developer might have mistakenly thought that changing the Precision Setting of a telemetry sensor ought to automatically be linked to a change in the "Ratio" of that telemetry sensor.  I.e. perhaps there was some confusion between the user-selectable "Precision Setting", and the inherent precision scale of a particular sensor.
