### ISSUE TITLE
2.3.10 TX16S: Active point does not follow curve in Input editor

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#8040]
If an input is specified with two or more lines (e.g. for dual rates), then the graphic is not displayed correctly if the line being displayed is inactive. Both on tx and in Companion.

**To Reproduce**
Download [minimalist setup](https://www.dropbox.com/s/bb6w9oeaejpy9u5/GitHub_CurveBug.otx?dl=0).
Switch SA up to activate first line of input 'Ew'
Open the input editor on the second line ('74%') of input 'Ew'.
Rotate S1

**Expected behavior**
The active point should follow the curve. It does not do so.
Works as expected in OTX 2.3.9.

![screenshot_tx16s_20-10-15_17-46-09](https://user-images.githubusercontent.com/6317479/96160833-61d15680-0f0e-11eb-8c60-8da74eef3eb3.png)

![screenshot_tx16s_20-10-15_17-27-18](https://user-images.githubusercontent.com/6317479/96160166-811bb400-0f0d-11eb-8908-a441d3ac9983.png)

**General information**
 - OpenTX 2.3.10 nightly, initially reported on 2.3.10 stable
 - OpenTX Companion 2.3.10 nightly
 - TX16S

**Comment by PD5DJ** [comment]
No need for a complex setup..

Even in Companion same Bug.


Just create a curve and see how ALL inputs follow CV1

Bug was also reported on RC-Groups.

![screenshot_x12s_20-10-15_16-28-36](https://user-images.githubusercontent.com/55426642/96161294-60585c00-0f17-11eb-914d-80d6011962fe.png)
![screenshot_x12s_20-10-15_16-28-51](https://user-images.githubusercontent.com/55426642/96161297-61898900-0f17-11eb-8c8b-fdff18ef075d.png)

**Comment by kilrah** [comment]
Already mentioned in related PR for author to comment. https://github.com/opentx/opentx/pull/7707

**Comment by bsongis** [comment]
oups :)

**Comment by lthole** [comment]
Reproduced on X10S 2.3.10

**Comment by Helifunster** [comment]
Why is this issue closed?

**Comment by 3djc** [comment]
Because it has been fixed in nightlies

**Comment by ahmad-kassem** [comment]
What do you mean fixed in nightlies?  How can we fix it on the radio?

**Comment by Helifunster** [comment]
Thank you. I think it was some spooky thing accordinly to Halloween season.

Regards


Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: 3djc<mailto:notifications@github.com>
Enviado: jueves, 29 de octubre de 2020 12:03 p. m.
Para: opentx/opentx<mailto:opentx@noreply.github.com>
CC: Helifunster<mailto:buzoech1@hotmail.com>; Comment<mailto:comment@noreply.github.com>
Asunto: Re: [opentx/opentx] 2.3.10 TX16S: Active point does not follow curve in Input editor (#8040)


Because it has been fixed in nightlies

**Comment by Helifunster** [comment]
Keep the superb job you are doing with OpenTX...but, the fastest, the better.

Regards

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: 3djc<mailto:notifications@github.com>
Enviado: jueves, 29 de octubre de 2020 12:03 p. m.
Para: opentx/opentx<mailto:opentx@noreply.github.com>
CC: Helifunster<mailto:buzoech1@hotmail.com>; Comment<mailto:comment@noreply.github.com>
Asunto: Re: [opentx/opentx] 2.3.10 TX16S: Active point does not follow curve in Input editor (#8040)


Because it has been fixed in nightlies

**Comment by KTM-250** [comment]
Hello, I too am having the issue of input stick movement following CV1 throttle curve.  I'm totally new here so I can't make sense of these comments, can someone please explain how to fix this issue? Thanks in advance...

**Comment by kilrah** [comment]
Update to OpenTX 2.3.11 that came out a week ago.

**Comment by KTM-250** [comment]
Wow, very cool, I was ready to set this thing on fire... Thank you for
responding!!
