### ISSUE TITLE
Cant use Trm5 as Source at input when i use same Trm5 to Inc Dec GlobalVariabel at Spezailfunktion

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#8180]
openTx V2.3.10
at TX16S and Horus X10

I use Trm5 for source at input and then went to mixer and Servo, all fine, all works when I move the Trm5, fine.  

Then I use Trm5 too at Spezialfunktion for Inc Dec the GlobalVariabel GV1 and Inc Dec GV1 works ok,
but since then Trm5 dont work as Input source, no change at Input5 when i move Trm5 

Then I change Trm5 to Trm6 at Inc/Dec for GV1 
and Trm5 at Inputs works again

Think there is an connection opened when I use Trm5 same time for changing GV

**Comment by kilrah** [comment]
Increment/decrement keeps normal trim function, Adjust with trim as source doesn't by design.

**Comment by hrenz** [comment]
Hy kilrah,
with TrimX as source I  can set exact values and Inc/Dec it in 1us or 2 us steps for a Sevotestprogram
I use the free Trm5 or Trm6 (or other trims) as source for Inputs/Mixer 
**AND** want to store the Value of Trm5 or Trm6 in a GVx too for other use

With analog  I can do it, 
so i was surpriced I cant do both with Trim switches
do it single it works Trm as source Inpu/Miscer **OR** Inc/Dec GVx

And its also not possible to use a GVx as Source for Input/Mixer

**Comment by kilrah** [comment]
When you do "Adjust GVAR" with a trim as source then whenever the function is enabled the trim maps to a separate register, so that you can use one trim to adjust multiple GVARs to different values AND still use it as normal trim. 

Doing it this way doesn't:
![Clipboard01](https://user-images.githubusercontent.com/6065069/103168593-c1b07b80-4834-11eb-9c91-aeafdfe4e488.png)

>And its also not possible to use a GVx as Source for Input/Mixer

You use MAX source and GVAR as weight, same thing.
