### ISSUE TITLE
Some german textstrings for smal LCD(X9-Lite) and large LCD (X9D+) are to long at spezialfunktion

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#8182]
Hy found 
some textstings are to long at Spezialfunktion settings

could someone change it at german version please
for X9D (large LCD) String Telemetrie  into Telemetry oder Telem.
for X9Lite (smal LCD) String Knüppel into GQHS

thanks

**Comment by fabo137** [comment]
> for X9Lite (smal LCD) String Knüppel into GQHS

I don't think that adding "CQHS" is a good idea. CQHS is basically the german translation of "TAER". If a user has other settings than TEAR e.g. AETR, it might be confusing and it would be wrong to put this translation string over here.
We can discuss about having "Sticks" instead of "Knüppel" because "Knüppel" in my opinion is quite colloquial when meaning a controlling mechanism like a joystick. The exact german translation would be "Steuerknüppel" which is even longer.

also changing the german term "Telemetrie" back to english is ratter a workaround than a real fix. 

I suggest to to close this issue, as the **correct** translation would result in **longer** **strings** and changing back a german word to english is not a real fix.

**Comment by hrenz** [comment]
Hy,
GQHS 

ans Sticks are ok

 
 
 
-----Ursprüngliche Mitteilung-----
Von: fabo137 ***@***.***>
An: opentx/opentx ***@***.***>
Cc: hrenz ***@***.***>; Author ***@***.***>
Verschickt: Fr, 19. Mrz 2021 7:09
Betreff: Re: [opentx/opentx] Some german textstrings for smal LCD(X9-Lite) and large LCD (X9D+) are to long at spezialfunktion (#8182)


for X9Lite (smal LCD) String Knüppel into GQHS
I don't think that adding "CQHS" is a good idea. CQHS is basically the german translation of "TAER". If a user has other settings than TEAR e.g. AETR, it might be confusing and wrong to put this translation string over here.
We can discuss about having "Sticks" instead of "Knüppel" because "Knüppel" in my opinion is quite colloquial when meaning a controlling mechanism like a joystick. The exact german translation would be "Steuerknüppel" which is even longer.also changing the german term "Telemetrie" back to english is ratter a workaround than a real fix.I suggest to to close this issue, as the correct translation would result in longer strings and changing back a german word to english is not a real fix.—
