### ISSUE TITLE
Cannot flash with dfu-util 0.10

### ISSUE THREAD

**Issue by nmaggioni** [opentx/opentx#8200]
**Describe the bug**

Writing a new firmware on the radio fails if `dfu-util` version 0.10 is used. Version 0.9 is working as expected.

Manually executing `/usr/bin/dfu-util -a 0 --dfuse-address 0x08000000:524288 --device 0483:df11  -U/tmp/33827-flash-check.bin` in a terminal, copy-pasted from the Configurator's window, works fine even with both `dfu-util` versions.

**To Reproduce**
1. Ensure that `dfu-util` 0.10 is installed.
2. Power off and connect the radio.
3. Click on "Write firmware to Radio" in the Configurator's sidebar.
4. Proceed with "Write to TX" without changing any option.
5. Encounter error.
6. Unplug the radio.
7. Downgrade to `dfu-util` 0.9.
8. Repeat steps 2-4.
9. No error should appear.

**Screenshots**

![flash_error](https://user-images.githubusercontent.com/3594528/104054279-1bc61f00-51ed-11eb-9aee-f2128e67fde4.png)

![unexpected_argument](https://user-images.githubusercontent.com/3594528/104054292-1ff23c80-51ed-11eb-86ac-970da980d86d.png)

**General information**
 - **OpenTX version:** upgrading from 2.3.10 to 2.3.11
 - **Hardware:** FrSky X-Lite S, Horus X10S
 - **OpenTX Companion:** 2.3.11 on Manjaro Linux 20.2.1

**Comment by 3djc** [comment]
Disable firmware check, and yes required version is 0.9.

**Comment by eff917** [comment]
The actual problem is an extra empty parameter before the last parameter, which in shell translates to a single extra space:
`[D] readFirmware():152 - readFirmware: reading "/home/eff/data/personal/FPV/Radio/TX16S/2.3.11/backup.bin" with "/usr/bin/dfu-util" ("-a", "0", "--dfuse-address", "0x08000000:2097152", "--device", "0483:df11", "", "-U/home/eff/data/personal/FPV/Radio/TX16S/2.3.11/backup.bin")`
