### ISSUE TITLE
Bootloader with Radiomaster TX16s and Open tx 2.3.11 (MacBook pro)

### ISSUE THREAD

**Issue by Gadget99** [opentx/opentx#8329]
Companion does not recognise my radio or SD card. I have been advised that i need to use Bootloader. The only way i can find to start the TX in boot mode is by holding switches 1 & 4 towards the middle whilst pressing the power button. This does not work and the controller boots normally. I have also updated the TX to the latest version of Open TX (2.3.11) via the SD card.
I know I can keep removing the sd card as required but it would be far simpler to be able to do it as designed through companion.

On another matter after updating to 2.3.11 only glider is shown on the new model screen on the transmitter.

Any help would to resolve would be appreciated.

**Comment by 3djc** [comment]
- if trims 1 and 4 pinched inward on power up do not start bootloader, then you need to reinstall it (please go to community support places like rcgroups or openrc forums for help on how to do that)
- the wizard issue is due to your Mac fiddling on the SDCard, you need to use CleanEject utility on your mac

**Comment by Gadget99** [comment]
Hi,
Are you referring to reinstalling companion or bootloader?

**Comment by 3djc** [comment]
the opentx botloader on the radio

**Comment by Gadget99** [comment]
Ok thanks. Ill give it a try
