### ISSUE TITLE
Deleting an input in companion "destroys" model

### ISSUE THREAD

**Issue by ProfDrYoMan** [opentx/opentx#8418]
**Describe the bug**
Deleting an input in companion "destroys" model

**To Reproduce**
See attached model file.

Before:
![image](https://user-images.githubusercontent.com/510353/113516505-e6766680-957a-11eb-9cfa-3a82d7310dcb.png)

Deleting I8:
![image](https://user-images.githubusercontent.com/510353/113516514-f3935580-957a-11eb-87b1-58e3bb325368.png)

Result:
![image](https://user-images.githubusercontent.com/510353/113516523-fa21cd00-957a-11eb-8879-c86fd0fd3f25.png)

Even L18 is gone completely!

**Expected behavior**
Deleting the input but nothing more.

**Screenshots**
See above

**General information**
 - OpenTX version 2.3.11
 - Hardware TX16s
 - OpenTX Companion 2.3.11 Windows

[Bug.zip](https://github.com/opentx/opentx/files/6255021/Bug.zip)

**Comment by elecpower** [comment]
In an attempt to maintain the many possible cross references, deleting an input, mix, etc can affect other configuration that refers to the deleted input, mix, etc or the effect of shuffling up the items below. This can trigger a cascade of updates throughout the model.
Without seeing your whole configuration for this model I cannot tell if this is working by design or you have found a bug.

**Comment by ProfDrYoMan** [comment]
That is why I added the otx. See last line of the report. Bug.zip.

**Comment by elecpower** [comment]
Apologies missed it. I'll take a look when I have some time over the next couple of days.

**Comment by elecpower** [comment]
Found the cause of your issue. The screenshot of your Logical Switches shows L18 referencing L11 which has no V1 activation switch. Before Delete
![bugLS](https://user-images.githubusercontent.com/15316949/113564456-c616dc80-964c-11eb-9a6f-827dd49ccb7b.jpg)
After Delete
![buglspost](https://user-images.githubusercontent.com/15316949/113566630-6cb0ac80-9650-11eb-97dd-eef8b7a1348b.jpg)

The model reference update iteratively tries to remove inactive/incomplete configuration because of the Delete action. However it can also remove pre-existing inactive/incomplete configuration.
In your case L11 is deleted as it has no activation switch in V1 which removes the V1 L11 switch from L18 (and everywhere else it is referenced) which causes L18 to be deleted and the switch in I11 to be removed.
Will need to review the logic to determine if, due to the iterative nature of the update, it is practical/possible to differentiate the cause of inactive/incomplete configuration.

**Comment by ProfDrYoMan** [comment]
Will look into my config there. It is possible that I missed something in L11. :)

**Comment by ProfDrYoMan** [comment]
Could remove L11 and trigger L18 with Act.
