### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by ghost** [opentx/opentx#8672]
Delete

**Comment by CarlouT** [comment]
Interaction from the Public on this issue here. https://www.facebook.com/groups/827280541160158/permalink/943994982822046/?comment_id=944003546154523&reply_comment_id=944028499485361&notif_id=1629408555367160&notif_t=group_comment&ref=notif

**Comment by CarlouT** [comment]
I guess for you guys to test this, look for a crappy SD card. Copy the necessary files and then plug it in the radio. All I did is to replace the old SD Card that I used by copying the contents of this card to the original SD card that came with the unit. And the issue went away. So I can confirm that the root cause of the issue is the SD card.

**Comment by CarlouT** [comment]
By the way, here's the old SD card that use. One year old. Its a reputable card.

![SD Card](https://user-images.githubusercontent.com/52803645/130173475-7631ddc2-4dea-4914-b0f1-aa60a661c99e.jpg)

**Comment by 3djc** [comment]
Clearly SD related, not OpenTX related
