### ISSUE TITLE
Companion update check failed, new version information not found

### ISSUE THREAD

**Issue by derpolygraf** [opentx/opentx#8723]
Hello, I have a issue with the open tx companion. After I start the program i get a error message: Companion update check failed, new version information not found, what should I do? I am using Win 10 and the newest companion version. Please help!

LG

**Comment by kilrah** [comment]
It's being solved right now, you will have to manually redownload and reinstall companion for update check and firmware downloads to work again.

**Comment by derpolygraf** [comment]
@kilrah thx for your answer, I reinstalled companion and disabled the automatic updat check up, but iam sitll not able to download a new Firmware: "Firmware update check failed, new version information not found or invalid."

**Comment by 3djc** [comment]
Yes problem is known and linked to https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/ A new repackaged version of Companion is going to be available soon

**Comment by kilrah** [comment]
I said it was being solved, not that it was ready yet... It now is.

http://www.open-tx.org/2021/10/01/companion-downloads

**Comment by mestafpv** [comment]
i think that not solved
![isue](https://user-images.githubusercontent.com/91732942/135611403-9f17f040-a74d-46ba-8a35-ce764da48691.png)

**Comment by kilrah** [comment]
If you had just downloaded it before it's likely your browser has cached the old file. Clear your browser cache.

**Comment by 3djc** [comment]
You can check with the about window

![image](https://user-images.githubusercontent.com/5167938/135611800-96658c1f-ec4b-43d5-ace2-7b28a6574e5e.png)

The new version says Oct 1st

**Comment by mestafpv** [comment]
thanks! 

> Si lo acababa de descargar antes, es probable que su navegador haya almacenado en caché el archivo anterior. Limpia la memoria caché de tu navegador.

thanks i will try :)

**Comment by Chappie6603** [comment]
Worked like a charm, definitely clear browser cache before downloading!!

Thanks for the fix!

**Comment by Taildragger1589** [comment]
Hi
Just received my Radiomaster tx16s running opentx 2.3.11.
Checked my root certificate at the site from your link and got a valid page.
Cleared my firefox cache
Downloaded and installed companion 2.3.14, for windows 10
still get the error messages for companion and opentx.
Don;t know what else to try...
Nick
![valid](https://user-images.githubusercontent.com/92655933/137606717-963faeea-195c-4949-a313-861cc8598d1c.JPG)

**Comment by Chappie6603** [comment]
Not sure about Firefox, I used edge, but should be the same.
Clear cache first, download new companion 2..3.14, install, and start.

Mike C.Canada
 

    On Saturday, October 16, 2021, 09:18:43 p.m. EDT, Taildragger1589 ***@***.***> wrote:  
 
 


Hi
Just received my Radiomaster tx16s running opentx 2.3.11.
Checked my root certificate at the site from your link and got a valid page.
Cleared my firefox cache
Downloaded and installed companion 2.3.14, for windows 10
still get the error messages for companion and opentx.
Don;t know what else to try...
Nick

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kilrah** [comment]
Usually that's when people messed up their installs and have companion installed multiple times in different folders.

**Comment by etskipsey** [comment]
Hi, Same problem, uninstalled companion, ensuring all bits were gone, reinstalled 2.3.9  (windows 10) same problems .  Suggestions?  Edgar

**Comment by 3djc** [comment]
ONLY version 2.3.14 dated Oct 1st will work, any older version will not, as the changes have nothing to do with companion per say, but overall ssl certification

**Comment by etskipsey** [comment]
Thanks, saves wasting my time, will update to 2.3.14  Help appreciated  Edgar

**Comment by Taildragger1589** [comment]
for those who've just about given up...

I finally got mine working after trying over and over with companion 2.3.14.
I cranked up file explorer and deleted everything I could find from opentx.
(the uninstall left a directory in programs 86 and 2 library files in c:/)
then I used the Edge browser instead of firefox to download the companion installer (after clearing the browser cache files)
After installing... it worked fine.
I now have updated firmware and SD card on my Tx16s.

**Comment by Chappie6603** [comment]
Nice work glad it is working.
Mike C.(retired RCAF)OntarioCanada 

    On Sunday, October 17, 2021, 08:32:57 p.m. EDT, Taildragger1589 ***@***.***> wrote:  
 
 


for those who've just about given up...

I finally got mine working after trying over and over with companion 2.3.14.
I cranked up file explorer and deleted everything I could find from opentx.
(the uninstall left a directory in programs 86 and 2 library files in c:/)
then I used the Edge browser instead of firefox to download the companion installer (after clearing the browser cache files)
After installing... it worked fine.
I now have updated firmware and SD card on my Tx16s.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
